// The `harness = "nextest"` lane: the linked nextest engine as a fast
// process-per-test EXECUTOR for a brokkr-configured sweep.
//
// An engine, not a policy source. Everything the lane runs and claims comes
// from brokkr.toml - that is the entire point of brokkr standing over a
// checkout it does not own - so the engine executes under a config brokkr
// SYNTHESIZES per run: retries zero, no default-filter, no test groups, no
// setup scripts, and `slow-timeout` + `terminate-after` set to brokkr's own
// per-test watchdog ceiling, which gives every test the hang kill the other
// lanes have, per process, for free. The project's `.config/nextest.toml` is
// NEVER opened and `NEXTEST_PROFILE` is never read: a foreign config must
// not get a vote in what a brokkr gate runs, and an earlier version of this
// lane that honoured it had to grow a pin/bless/drift apparatus just to
// police the vote it had granted.
//
// What the engine is FOR: dissolving per-test serialization. A sweep that
// needs process isolation (the `isolation = "process"` semantics) is N
// sequential `cargo test -- --exact` spawns on the libtest path; here it is
// the same guarantee executed concurrently. The in-process libtest lanes
// remain the default everywhere else - a shared-process lane is the only
// detector for the process-global-state class, and this lane deliberately
// does not replace it.
//
// The division of labour:
// - Brokkr owns the COMPILE SHAPE. The build is brokkr's cargo invocation
//   (selection, features, unification pin, cargo profile, [lints] allows,
//   sweep env, rustflags plumbing), streamed into nextest's
//   BinaryListBuilder - so a nextest lane and a libtest lane with equal
//   compile inputs share the target dir and the clippy dedupe.
// - Brokkr owns the FILTERS. The sweep's `only`/`skip` map onto nextest's
//   own TestFilterPatterns (identical libtest substring semantics, no
//   filterset string to escape); a package-qualified skip becomes the
//   filterset `not (package(P) & test(~X))`, folding the one predicate
//   brokkr used to evaluate itself back into the tool.
// - Brokkr owns CONCURRENCY: the profile's `test_threads` maps onto the
//   engine's in-flight count (unset = the engine's num-cpus default).
// - The engine owns execution and rendering: process-per-test scheduling
//   and its reporter. Brokkr wraps it in the usual sweep lines and decides
//   pass/fail from RunStats.
//
// The linked engine's version is brokkr's pin, not the host's. It is
// recorded below and printed on the lane's header line, so a result says
// which engine produced it.

use camino::Utf8PathBuf;
use guppy::graph::PackageGraph;
use nextest_filtering::{Filterset, FiltersetKind, ParseContext};
use nextest_runner::{
    cargo_config::{CargoConfigs, EnvironmentMap},
    config::core::NextestConfig,
    double_spawn::DoubleSpawnInfo,
    input::InputHandlerKind,
    list::{
        BinaryListBuilder, ListProgressOptions, RustTestArtifact, TestExecuteContext, TestList,
    },
    platform::{BuildPlatforms, HostPlatform, PlatformLibdir},
    helpers::{ShowTerminalProgress, ThemeCharacters},
    reporter::{ReporterBuilder, ReporterOutput, ShowProgress, structured::StructuredReporter},
    reuse_build::PathMapper,
    run_mode::NextestRunMode,
    runner::{TestRunnerBuilder, VersionEnvVars, configure_handle_inheritance},
    signal::SignalHandlerKind,
    target_runner::TargetRunner,
    test_filter::{FilterBound, RunIgnored, TestFilter, TestFilterPatterns},
};

/// The linked nextest-runner version, printed on the lane header so a result
/// names the engine that produced it. Must track Cargo.toml's pin - there is
/// no runtime accessor on the crate, and a compile-time drift here would
/// only mislabel output, never change behaviour.
const NEXTEST_ENGINE_VERSION: &str = "0.122.1";

/// The engine config brokkr synthesizes for one run. Written under the
/// brokkr-owned state dir (never into the code tree) and handed to the
/// engine as its ONLY config file, which is what replaces - not merely
/// shadows - any `.config/nextest.toml` the checkout carries.
fn write_synthesized_config(state_root: &Path) -> Result<Utf8PathBuf, DevError> {
    let dir = state_root.join(".brokkr");
    std::fs::create_dir_all(&dir)?;
    let path = dir.join("nextest-synth.toml");
    let ceiling = test_runner::TEST_TIMEOUT.as_secs();
    // `terminate-after = 1`: the first time a test crosses the ceiling it is
    // terminated, the exact semantics of the libtest lanes' watchdog.
    let body = format!(
        "# Generated by brokkr on every nextest-lane run; do not edit.\n\
         [profile.default]\n\
         retries = 0\n\
         slow-timeout = {{ period = \"{ceiling}s\", terminate-after = 1, grace-period = \"1s\" }}\n"
    );
    std::fs::write(&path, body)?;
    Utf8PathBuf::from_path_buf(path)
        .map_err(|p| DevError::Config(format!("state dir is not UTF-8: {}", p.display())))
}

/// Run one `harness = "nextest"` sweep. Returns `Ok(false)` when the run
/// failed, having already reported it. An `Err` leaving this lane carries
/// its whole diagnostic in the message; `run_test_phase`'s caller voices it
/// (the summary path prints only the timing line).
#[allow(clippy::too_many_arguments, clippy::too_many_lines)]
fn run_nextest_sweep(
    project_root: &Path,
    state_root: &Path,
    sweep: &ResolvedSweep,
    packages: &[&str],
    extra_args: &[String],
    project_env: &[(String, String)],
    allow_args: &[String],
    commands: bool,
) -> Result<bool, DevError> {
    let (cargo_extra, libtest_extra) = split_extra_args(extra_args);
    if !libtest_extra.is_empty() {
        return Err(DevError::Config(format!(
            "sweep '{}' runs under the nextest engine, which takes no raw libtest args; drop \
             the trailing `-- {}` (use the sweep's `skip`/`only`).",
            sweep.label,
            libtest_extra.join(" ")
        )));
    }
    reject_unsupported_forwarded(sweep, cargo_extra)?;

    let env_full = merged_env(&sweep.env, project_env);
    let env_refs: Vec<(&str, &str)> = env_full
        .iter()
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();

    output::run_msg(&format!(
        "test {}: nextest engine {NEXTEST_ENGINE_VERSION}, process-per-test, brokkr-owned config",
        sweep.label
    ));

    // The graph feeds config parsing (filterset predicates, test groups) and
    // artifact resolution. `--all-features --filter-platform` mirrors what
    // cargo-nextest itself asks for - the graph is a naming universe, not the
    // build's resolution.
    let host = HostPlatform::detect(PlatformLibdir::from_rustc_stdout(
        nextest_runner::RustcCli::print_host_libdir().read(),
    ))
    .map_err(|e| DevError::Build(format!("nextest host platform detection failed: {e}")))?;
    let triple = host.platform.triple_str().to_owned();
    let build_platforms = BuildPlatforms { host, target: None };

    let metadata = output::run_captured_with_env(
        "cargo",
        &[
            "metadata",
            "--format-version=1",
            "--all-features",
            "--filter-platform",
            &triple,
        ],
        project_root,
        &env_refs,
    )?;
    if !metadata.status.success() {
        output::error(&String::from_utf8_lossy(&metadata.stderr));
        return Err(DevError::Build("cargo metadata failed".into()));
    }
    let metadata_json = String::from_utf8_lossy(&metadata.stdout).into_owned();
    let graph = PackageGraph::from_json(&metadata_json)
        .map_err(|e| DevError::Build(format!("cargo metadata unparseable: {e}")))?;
    let workspace_root: Utf8PathBuf = graph.workspace().root().to_owned();

    let cargo_configs = CargoConfigs::new(Vec::<String>::new())
        .map_err(|e| DevError::Config(format!("cargo config discovery failed: {e}")))?;

    // The build is brokkr's: the same compile-shape argv every other lane
    // uses, streamed into nextest's builder so the artifact facts (binary
    // ids, build meta, dylib paths) are nextest's own reading of it.
    let mut args: Vec<String> = vec!["test".into(), "--no-run".into(), "--message-format=json".into()];
    args.extend(sweep_selection_args(sweep, packages));
    args.extend(allow_args.iter().cloned());
    args.extend(cargo_extra.iter().cloned());
    args.extend(sweep.unification_args());
    if let Some(p) = sweep.profile {
        args.extend(p.cargo_args().iter().map(|s| (*s).to_owned()));
    }
    if !has_target_selector(&args) {
        args.push("--tests".into());
    }
    if commands {
        output::run_msg(&format!("cargo {}", args.join(" ")));
    }
    let arg_refs: Vec<&str> = args.iter().map(String::as_str).collect();
    let build = output::run_captured_with_env("cargo", &arg_refs, project_root, &env_refs)?;
    if !build.status.success() {
        output::error(&format!("failing command: cargo {}", args.join(" ")));
        output::error(&String::from_utf8_lossy(&build.stderr));
        return Ok(false);
    }
    let mut builder = BinaryListBuilder::new(&graph, build_platforms.clone());
    for line in String::from_utf8_lossy(&build.stdout).lines() {
        builder
            .process_message_line(line)
            .map_err(|e| DevError::Build(format!("nextest could not read the build: {e}")))?;
    }
    let binary_list = std::sync::Arc::new(builder.finish());

    // The engine's config is brokkr's own synthesized file, passed as the
    // explicit config source so the checkout's `.config/nextest.toml` (if
    // any) is never consulted, and `NEXTEST_PROFILE` is never read: a
    // foreign config gets no vote in what a brokkr sweep runs.
    let synth = write_synthesized_config(state_root)?;
    let pcx = ParseContext::new(&graph);
    let config = NextestConfig::from_sources(
        workspace_root.clone(),
        &pcx,
        Some(synth.as_path()),
        std::iter::empty::<&nextest_runner::config::core::ToolConfigFile>(),
        &std::collections::BTreeSet::new(),
    )
    .map_err(|e| DevError::Config(format!("nextest engine config: {e}")))?;
    let early_profile = config
        .profile(NextestConfig::DEFAULT_PROFILE)
        .map_err(|e| DevError::Config(format!("nextest engine profile: {e}")))?;
    let known_groups = early_profile.known_groups();
    let profile = early_profile.apply_build_platforms(&build_platforms);

    // Filters: `only` and unqualified `skip` ride nextest's own libtest
    // pattern emulation (same substring semantics, nothing to escape);
    // package-qualified skips become one filterset each. Compiled by the
    // same function the audit's listing uses, so run and audit can never
    // disagree about what a sweep selects.
    let test_filter = sweep_engine_filter(sweep, &pcx, &known_groups)?;

    // Double-spawn re-invokes the CURRENT executable with a `__double-spawn`
    // subcommand - a protocol cargo-nextest's own binary implements and
    // brokkr does not, so enabling it makes every test command a brokkr clap
    // error. Disabled is a supported nextest mode (NEXTEST_DOUBLE_SPAWN=0);
    // the cost is a narrow unix signal race around spawn, not correctness of
    // results.
    let double_spawn = DoubleSpawnInfo::disabled();
    let target_runner =
        TargetRunner::new(&cargo_configs, &build_platforms).unwrap_or_else(|_| TargetRunner::empty());
    let run_id = nextest_runner::helpers::force_or_new_run_id();
    let version_env_vars = VersionEnvVars {
        current_version: NEXTEST_ENGINE_VERSION
            .parse()
            .map_err(|e| DevError::Build(format!("engine version constant: {e}")))?,
        required_version: None,
        recommended_version: None,
    };
    let ctx = TestExecuteContext {
        run_id,
        version_env_vars: &version_env_vars,
        profile_name: profile.name(),
        double_spawn: &double_spawn,
        target_runner: &target_runner,
    };

    let path_mapper = PathMapper::noop();
    let rust_build_meta = binary_list.rust_build_meta.map_paths(&path_mapper);
    let test_artifacts = RustTestArtifact::from_binary_list(
        &graph,
        std::sync::Arc::clone(&binary_list),
        &rust_build_meta,
        &path_mapper,
        None,
    )
    .map_err(|e| DevError::Build(format!("nextest artifact resolution: {e}")))?;
    let env_map = EnvironmentMap::new(&cargo_configs);
    let test_list = TestList::new(
        &ctx,
        test_artifacts,
        rust_build_meta,
        &test_filter,
        None,
        workspace_root.clone(),
        env_map,
        &profile,
        // `All`, explicitly: the synthesized config has no default-filter,
        // and the concept must never re-enter through a bound.
        FilterBound::All,
        nextest_runner::config::core::get_num_cpus(),
        ListProgressOptions::new(
            ShowProgress::None,
            ShowTerminalProgress::from_cargo_configs(&cargo_configs, false),
            ThemeCharacters::default(),
            false,
        ),
    )
    .map_err(|e| DevError::Build(format!("nextest listing failed: {e}")))?;

    if test_list.run_count() == 0 {
        return Err(DevError::Config(format!(
            "cargo test: zero tests ran (sweep: {}) - the sweep's filters selected no work; \
             treat as a wrong-run.",
            sweep.label
        )));
    }

    // Concurrency is brokkr policy: the profile's `test_threads` maps onto
    // the engine's in-flight count. Unset (or 0) leaves the engine's
    // num-cpus default; there is no serial-by-default here, because
    // process-per-test needs no watchdog attribution trick - the synthesized
    // slow-timeout kills a hung test by name at any concurrency.
    let mut runner_builder = TestRunnerBuilder::default();
    // Every brokkr lane enumerates all failures in one run (the libtest
    // lanes' --no-fail-fast); the engine's default cancels on the first,
    // which under-reports a red tree.
    runner_builder.set_max_fail(nextest_runner::config::elements::MaxFail::All);
    if let Some(n) = sweep.test_threads
        && n >= 1
    {
        let count = i64::from(n).try_into().map_err(|_| {
            DevError::Config(format!("test_threads = {n} does not fit the engine's count"))
        })?;
        runner_builder
            .set_test_threads(nextest_runner::config::elements::TestThreads::Count(count));
    }
    let runner = runner_builder
        .build(
            run_id,
            version_env_vars.clone(),
            &test_list,
            &profile,
            std::env::args().collect(),
            SignalHandlerKind::Standard,
            InputHandlerKind::Noop,
            double_spawn.clone(),
            target_runner.clone(),
        )
        .map_err(|e| DevError::Build(format!("nextest runner: {e}")))?;

    let mut reporter = ReporterBuilder::default().build(
        &test_list,
        &profile,
        ShowTerminalProgress::from_cargo_configs(&cargo_configs, false),
        ReporterOutput::Terminal,
        StructuredReporter::new(),
    );

    configure_handle_inheritance(false)
        .map_err(|e| DevError::Build(format!("nextest handle setup: {e}")))?;
    let run_stats = runner
        .try_execute(|event| reporter.report_event(event))
        .map_err(|e| DevError::Build(format!("nextest run failed to execute: {e}")))?;
    let _ = reporter.finish();

    let passed = run_stats.summarize_final();
    Ok(matches!(
        passed,
        nextest_runner::reporter::events::FinalRunStats::Success
    ))
}

/// One testcase from an engine listing, as plain data: the audit's view of
/// what a nextest lane selects. `binary_id` is nextest's own
/// `RustBinaryId` rendering, the finer half of the (binary-id, test)
/// coverage pair.
struct EngineCase {
    binary_id: String,
    test: String,
    disposition: Disposition,
}

/// List one nextest sweep's testcases through the engine, without running
/// anything: build (or no-op re-check) the shape, feed the artifact stream
/// to `BinaryListBuilder`, and read `TestList`'s per-testcase verdicts under
/// the sweep's real filters. The coverage audit's source for a nextest
/// lane's ran-set - enumeration is ground truth, so the lane's claim comes
/// from the same engine that executes it, never from a reimplementation of
/// its filter semantics.
#[allow(clippy::too_many_lines)]
fn nextest_shape_cases(
    project_root: &Path,
    state_root: &Path,
    sweep: &ResolvedSweep,
    selection: &[String],
    env_refs: &[(&str, &str)],
    commands: bool,
) -> Result<Vec<EngineCase>, DevError> {
    let host = HostPlatform::detect(PlatformLibdir::from_rustc_stdout(
        nextest_runner::RustcCli::print_host_libdir().read(),
    ))
    .map_err(|e| DevError::Build(format!("nextest host platform detection failed: {e}")))?;
    let triple = host.platform.triple_str().to_owned();
    let build_platforms = BuildPlatforms { host, target: None };

    let metadata = output::run_captured_with_env(
        "cargo",
        &["metadata", "--format-version=1", "--all-features", "--filter-platform", &triple],
        project_root,
        env_refs,
    )?;
    if !metadata.status.success() {
        output::error(&String::from_utf8_lossy(&metadata.stderr));
        return Err(DevError::Build("cargo metadata failed".into()));
    }
    let metadata_json = String::from_utf8_lossy(&metadata.stdout).into_owned();
    let graph = PackageGraph::from_json(&metadata_json)
        .map_err(|e| DevError::Build(format!("cargo metadata unparseable: {e}")))?;
    let workspace_root: Utf8PathBuf = graph.workspace().root().to_owned();
    let cargo_configs = CargoConfigs::new(Vec::<String>::new())
        .map_err(|e| DevError::Config(format!("cargo config discovery failed: {e}")))?;

    let mut args: Vec<String> =
        vec!["test".into(), "--no-run".into(), "--message-format=json".into()];
    args.extend(selection.iter().cloned());
    if !has_target_selector(&args) {
        args.push("--tests".into());
    }
    if commands {
        output::run_msg(&format!("cargo {}", args.join(" ")));
    }
    let arg_refs: Vec<&str> = args.iter().map(String::as_str).collect();
    let build = output::run_captured_with_env("cargo", &arg_refs, project_root, env_refs)?;
    if !build.status.success() {
        output::error(&format!("failing command: cargo {}", args.join(" ")));
        output::error(&String::from_utf8_lossy(&build.stderr));
        return Err(DevError::Build("coverage enumeration failed".into()));
    }
    let mut builder = BinaryListBuilder::new(&graph, build_platforms.clone());
    for line in String::from_utf8_lossy(&build.stdout).lines() {
        builder
            .process_message_line(line)
            .map_err(|e| DevError::Build(format!("nextest could not read the build: {e}")))?;
    }
    let binary_list = std::sync::Arc::new(builder.finish());

    let synth = write_synthesized_config(state_root)?;
    let pcx = ParseContext::new(&graph);
    let config = NextestConfig::from_sources(
        workspace_root.clone(),
        &pcx,
        Some(synth.as_path()),
        std::iter::empty::<&nextest_runner::config::core::ToolConfigFile>(),
        &std::collections::BTreeSet::new(),
    )
    .map_err(|e| DevError::Config(format!("nextest engine config: {e}")))?;
    let early_profile = config
        .profile(NextestConfig::DEFAULT_PROFILE)
        .map_err(|e| DevError::Config(format!("nextest engine profile: {e}")))?;
    let known_groups = early_profile.known_groups();
    let profile = early_profile.apply_build_platforms(&build_platforms);

    let test_filter = sweep_engine_filter(sweep, &pcx, &known_groups)?;
    let double_spawn = DoubleSpawnInfo::disabled();
    let target_runner = TargetRunner::new(&cargo_configs, &build_platforms)
        .unwrap_or_else(|_| TargetRunner::empty());
    let run_id = nextest_runner::helpers::force_or_new_run_id();
    let version_env_vars = VersionEnvVars {
        current_version: NEXTEST_ENGINE_VERSION
            .parse()
            .map_err(|e| DevError::Build(format!("engine version constant: {e}")))?,
        required_version: None,
        recommended_version: None,
    };
    let ctx = TestExecuteContext {
        run_id,
        version_env_vars: &version_env_vars,
        profile_name: profile.name(),
        double_spawn: &double_spawn,
        target_runner: &target_runner,
    };
    let path_mapper = PathMapper::noop();
    let rust_build_meta = binary_list.rust_build_meta.map_paths(&path_mapper);
    let test_artifacts = RustTestArtifact::from_binary_list(
        &graph,
        std::sync::Arc::clone(&binary_list),
        &rust_build_meta,
        &path_mapper,
        None,
    )
    .map_err(|e| DevError::Build(format!("nextest artifact resolution: {e}")))?;
    let env_map = EnvironmentMap::new(&cargo_configs);
    let test_list = TestList::new(
        &ctx,
        test_artifacts,
        rust_build_meta,
        &test_filter,
        None,
        workspace_root,
        env_map,
        &profile,
        FilterBound::All,
        nextest_runner::config::core::get_num_cpus(),
        ListProgressOptions::new(
            ShowProgress::None,
            ShowTerminalProgress::from_cargo_configs(&cargo_configs, false),
            ThemeCharacters::default(),
            false,
        ),
    )
    .map_err(|e| DevError::Build(format!("nextest listing failed: {e}")))?;

    Ok(test_list
        .iter_tests()
        .map(|t| EngineCase {
            binary_id: t.id().binary_id.to_string(),
            test: t.id().test_name.to_string(),
            disposition: nextest_disposition(&t.test_info.filter_match),
        })
        .collect())
}

/// The sweep's filters compiled onto the engine's own surfaces - shared by
/// the run lane and the audit listing so the two can never disagree about
/// what a sweep selects.
fn sweep_engine_filter(
    sweep: &ResolvedSweep,
    pcx: &ParseContext<'_>,
    known_groups: &nextest_filtering::KnownGroups,
) -> Result<TestFilter, DevError> {
    let mut patterns = TestFilterPatterns::new(sweep.name_filters.clone());
    let mut run_ignored = RunIgnored::default();
    let mut it = sweep.libtest_args.iter();
    while let Some(tok) = it.next() {
        match tok.as_str() {
            "--skip" => {
                let Some(v) = it.next() else {
                    return Err(DevError::Config("--skip without a value".into()));
                };
                patterns.add_skip_pattern(v.clone());
            }
            "--include-ignored" => run_ignored = RunIgnored::All,
            other => {
                return Err(DevError::Config(format!(
                    "sweep '{}' carries libtest arg `{other}`, which the nextest lane cannot \
                     translate; drop it from the profile, or use a libtest entry.",
                    sweep.label
                )));
            }
        }
    }
    let mut filtersets: Vec<Filterset> = Vec::new();
    for qs in &sweep.qualified_skips {
        let expr = qualified_skip_filterset(qs)?;
        let parsed = Filterset::parse(expr.clone(), pcx, FiltersetKind::Test, known_groups)
            .map_err(|e| {
                DevError::Config(format!("qualified skip `{expr}` did not compile: {e:?}"))
            })?;
        filtersets.push(parsed);
    }
    TestFilter::new(NextestRunMode::Test, run_ignored, patterns, filtersets)
        .map_err(|e| DevError::Config(format!("nextest test filter: {e}")))
}

/// The filterset for one package-qualified skip: exclude tests matching the
/// pattern *within that package only*, exactly the semantics brokkr's own
/// evaluator gives the libtest lanes.
///
/// Values are interpolated into filterset source text, so the charset is
/// restricted to what a test path or package name can contain - anything
/// else is refused rather than escaped, because a wrongly-escaped filter
/// silently changes which tests run.
fn qualified_skip_filterset(qs: &crate::config::QualifiedSkip) -> Result<String, DevError> {
    let ok = |s: &str| {
        !s.is_empty()
            && s.chars()
                .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | ':' | '-'))
    };
    if !ok(&qs.package) || !ok(&qs.pattern) {
        return Err(DevError::Config(format!(
            "qualified skip {{ package = \"{}\", pattern = \"{}\" }} contains characters the \
             nextest filterset translation does not interpolate; use a libtest entry for this \
             shape.",
            qs.package, qs.pattern
        )));
    }
    Ok(format!("not (package({}) & test(~{}))", qs.package, qs.pattern))
}

