//! Gate database for ratatoskr `sync --bench` regression gating.
//!
//! Per-project SQLite DB at `.brokkr/ratatoskr/gate.db` (committed,
//! same convention as `.brokkr/results.db`). One row per gated
//! `sync --bench` run. Baselines are pure pointers in `brokkr.toml`
//! (`[ratatoskr.gate.<name>.baseline].<hostname>`); they don't change
//! the write path.
//!
//! See `docs/commands/ratatoskr-gate.md` for the full design.

use std::path::Path;

use rusqlite::Connection;

use super::types::generate_uuid;
use crate::error::DevError;

const SCHEMA_VERSION: i64 = 1;

const CREATE_TABLE: &str = "\
CREATE TABLE IF NOT EXISTS gate_runs (
    uuid          TEXT PRIMARY KEY,
    created_at    INTEGER NOT NULL,
    git_commit    TEXT NOT NULL,
    dirty         INTEGER NOT NULL,
    hostname      TEXT NOT NULL,
    gate_name     TEXT NOT NULL,
    script        TEXT NOT NULL,
    fixture       TEXT NOT NULL,
    profile       TEXT NOT NULL,
    elapsed_ms    INTEGER NOT NULL,
    exit_code     INTEGER NOT NULL,
    success       INTEGER NOT NULL,
    sidecar       TEXT NOT NULL,
    meta          TEXT NOT NULL
)";

const CREATE_INDEX: &str = "\
    CREATE INDEX IF NOT EXISTS idx_gate_runs_lookup \
    ON gate_runs(gate_name, hostname, created_at)";

pub struct GateDb {
    conn: Connection,
}

/// Row data for insertion. The `uuid` is generated by `insert`.
pub struct GateRow {
    pub git_commit: String,
    pub dirty: bool,
    pub hostname: String,
    pub gate_name: String,
    pub script: String,
    pub fixture: String,
    pub profile: String,
    pub elapsed_ms: i64,
    pub exit_code: i32,
    pub success: bool,
    /// JSON-serialized sidecar blob (object).
    pub sidecar: String,
    /// JSON-serialized meta blob (object). Mirrors `summary.json` ingestion.
    pub meta: String,
}

/// Row data returned from queries (full row including generated `uuid`
/// and `created_at`).
#[allow(dead_code)]
#[derive(Debug)]
pub struct GateEntry {
    pub uuid: String,
    pub created_at: i64,
    pub git_commit: String,
    pub dirty: bool,
    pub hostname: String,
    pub gate_name: String,
    pub script: String,
    pub fixture: String,
    pub profile: String,
    pub elapsed_ms: i64,
    pub exit_code: i32,
    pub success: bool,
    pub sidecar: String,
    pub meta: String,
}

impl GateDb {
    /// Open (or create) the gate database at `path`.
    pub fn open(path: &Path) -> Result<Self, DevError> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let conn = Connection::open(path)?;
        conn.pragma_update(None, "journal_mode", "WAL")?;
        run_migrations(&conn)?;
        conn.execute_batch(CREATE_TABLE)?;
        conn.execute_batch(CREATE_INDEX)?;
        conn.pragma_update(None, "user_version", SCHEMA_VERSION)?;
        Ok(Self { conn })
    }

    /// Insert a row, returning its newly generated UUID.
    pub fn insert(&self, row: &GateRow) -> Result<String, DevError> {
        let uuid = generate_uuid()?;
        let created_at = unix_now();
        self.conn.execute(
            "INSERT INTO gate_runs (\
                uuid, created_at, git_commit, dirty, hostname, gate_name, \
                script, fixture, profile, elapsed_ms, exit_code, success, \
                sidecar, meta\
             ) VALUES (\
                ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14\
             )",
            rusqlite::params![
                uuid,
                created_at,
                row.git_commit,
                i64::from(row.dirty),
                row.hostname,
                row.gate_name,
                row.script,
                row.fixture,
                row.profile,
                row.elapsed_ms,
                row.exit_code,
                i64::from(row.success),
                row.sidecar,
                row.meta,
            ],
        )?;
        Ok(uuid)
    }

    /// Resolve a pinned baseline to exactly one row on `hostname`.
    ///
    /// The pin is a full UUID or a prefix of one, and it must resolve
    /// **unambiguously**: an exact match wins, a prefix matching one row
    /// resolves to it, and a prefix matching several is refused rather
    /// than resolved newest-wins - otherwise a later run that happened to
    /// share the pinned prefix would silently become the baseline. An
    /// empty or whitespace-bearing pin is refused outright, since it
    /// prefix-matches everything.
    ///
    /// `exclude_uuid` is the run being evaluated. The gate hook inserts
    /// it before the lookup, so without the exclusion a short pin could
    /// match the current row and make it its own baseline - where
    /// `max_delta = 0` and `equal_to_baseline` pass by construction.
    ///
    /// Matching is a byte-exact `substr` comparison, not `LIKE`: `%` and
    /// `_` in a pin are ordinary characters, never wildcards.
    ///
    /// Returns `Ok(None)` when no row matches.
    pub fn lookup_baseline(
        &self,
        pin: &str,
        hostname: &str,
        exclude_uuid: &str,
    ) -> Result<Option<GateEntry>, DevError> {
        let pin_len = validate_pin(pin)?;
        let mut stmt = self.conn.prepare(
            "SELECT uuid, created_at, git_commit, dirty, hostname, gate_name, \
                    script, fixture, profile, elapsed_ms, exit_code, success, \
                    sidecar, meta \
             FROM gate_runs \
             WHERE substr(uuid, 1, ?2) = ?1 AND hostname = ?3 AND uuid != ?4 \
             ORDER BY uuid LIMIT ?5",
        )?;
        let mut rows = stmt
            .query_map(
                rusqlite::params![pin, pin_len, hostname, exclude_uuid, AMBIGUITY_LISTING + 1],
                row_to_entry,
            )?
            .collect::<rusqlite::Result<Vec<_>>>()?;
        if let Some(idx) = rows.iter().position(|r| r.uuid == pin) {
            return Ok(Some(rows.swap_remove(idx)));
        }
        match rows.len() {
            0 => Ok(None),
            1 => Ok(rows.pop()),
            n => {
                let listed: Vec<&str> = rows
                    .iter()
                    .take(usize::try_from(AMBIGUITY_LISTING).unwrap_or(usize::MAX))
                    .map(|r| r.uuid.as_str())
                    .collect();
                let more = if i64::try_from(n).unwrap_or(i64::MAX) > AMBIGUITY_LISTING {
                    ", ..."
                } else {
                    ""
                };
                Err(DevError::Config(format!(
                    "baseline pin `{pin}` is ambiguous on host `{hostname}`: it is a \
                     prefix of several gate.db rows ({}{more}). Pin the full UUID.",
                    listed.join(", ")
                )))
            }
        }
    }

    /// Hostnames that have a row matching `pin` (exact or prefix, same
    /// byte-exact matching as [`GateDb::lookup_baseline`]), ignoring the
    /// hostname scope `lookup_baseline` applies. Lets a failed baseline
    /// lookup say whether the UUID is absent outright or merely filed
    /// under a different machine - two conditions with different remedies.
    pub fn hosts_with_uuid(&self, pin: &str) -> Result<Vec<String>, DevError> {
        let pin_len = validate_pin(pin)?;
        let mut stmt = self.conn.prepare(
            "SELECT DISTINCT hostname FROM gate_runs \
             WHERE substr(uuid, 1, ?2) = ?1 ORDER BY hostname",
        )?;
        let rows = stmt.query_map(rusqlite::params![pin, pin_len], |r| r.get::<_, String>(0))?;
        rows.collect::<rusqlite::Result<Vec<_>>>()
            .map_err(DevError::from)
    }

    /// How many rows this gate has on this host, excluding `exclude_uuid`
    /// (the run being evaluated, which the gate hook has already inserted).
    /// A pinned-but-missing baseline over an otherwise-empty history is the
    /// signature of local `gate.db` loss rather than a bad pin.
    pub fn count_for_gate(
        &self,
        gate_name: &str,
        hostname: &str,
        exclude_uuid: &str,
    ) -> Result<i64, DevError> {
        self.conn
            .query_row(
                "SELECT COUNT(*) FROM gate_runs \
                 WHERE gate_name = ?1 AND hostname = ?2 AND uuid != ?3",
                rusqlite::params![gate_name, hostname, exclude_uuid],
                |r| r.get(0),
            )
            .map_err(DevError::from)
    }
}

/// How many candidate UUIDs an ambiguous-pin error lists.
const AMBIGUITY_LISTING: i64 = 5;

/// Refuse a pin that cannot identify one row, and return its length in
/// characters (what SQLite's `substr` counts). An empty pin is a prefix
/// of every UUID; whitespace only arises from a mangled paste.
fn validate_pin(pin: &str) -> Result<i64, DevError> {
    if pin.is_empty() {
        return Err(DevError::Config(
            "baseline pin is empty - it would match every gate.db row. \
             Pin the UUID printed by --as-baseline."
                .into(),
        ));
    }
    if pin.chars().any(char::is_whitespace) {
        return Err(DevError::Config(format!(
            "baseline pin `{pin}` contains whitespace - pin the UUID printed by --as-baseline"
        )));
    }
    Ok(i64::try_from(pin.chars().count()).unwrap_or(i64::MAX))
}

fn row_to_entry(row: &rusqlite::Row<'_>) -> rusqlite::Result<GateEntry> {
    Ok(GateEntry {
        uuid: row.get(0)?,
        created_at: row.get(1)?,
        git_commit: row.get(2)?,
        dirty: row.get::<_, i64>(3)? != 0,
        hostname: row.get(4)?,
        gate_name: row.get(5)?,
        script: row.get(6)?,
        fixture: row.get(7)?,
        profile: row.get(8)?,
        elapsed_ms: row.get(9)?,
        exit_code: row.get(10)?,
        success: row.get::<_, i64>(11)? != 0,
        sidecar: row.get(12)?,
        meta: row.get(13)?,
    })
}

fn unix_now() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| i64::try_from(d.as_secs()).unwrap_or(i64::MAX))
        .unwrap_or(0)
}

fn run_migrations(conn: &Connection) -> Result<(), DevError> {
    if !has_table(conn, "gate_runs") {
        return Ok(());
    }
    let current: i64 = conn.pragma_query_value(None, "user_version", |r| r.get(0))?;
    if current >= SCHEMA_VERSION {
        return Ok(());
    }
    // Future migrations go here.
    conn.pragma_update(None, "user_version", SCHEMA_VERSION)?;
    Ok(())
}

fn has_table(conn: &Connection, table: &str) -> bool {
    conn.query_row(
        "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=?1",
        [table],
        |row| row.get::<_, i64>(0),
    )
    .map(|count| count > 0)
    .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]
    use super::*;

    fn open_mem() -> GateDb {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(CREATE_TABLE).unwrap();
        conn.execute_batch(CREATE_INDEX).unwrap();
        conn.pragma_update(None, "user_version", SCHEMA_VERSION)
            .unwrap();
        GateDb { conn }
    }

    fn sample_row() -> GateRow {
        GateRow {
            git_commit: "abc123".into(),
            dirty: false,
            hostname: "host-a".into(),
            gate_name: "jmap_small".into(),
            script: "tests/sync/jmap.lua".into(),
            fixture: "jmap-init".into(),
            profile: "release".into(),
            elapsed_ms: 1234,
            exit_code: 0,
            success: true,
            sidecar: "{}".into(),
            meta: r#"{"correct":1}"#.into(),
        }
    }

    /// Insert a row under a chosen UUID, so prefix collisions can be
    /// staged deterministically.
    fn insert_with_uuid(db: &GateDb, uuid: &str) {
        let row = sample_row();
        db.conn
            .execute(
                "INSERT INTO gate_runs (uuid, created_at, git_commit, dirty, hostname, \
                 gate_name, script, fixture, profile, elapsed_ms, exit_code, success, \
                 sidecar, meta) VALUES (?1, 0, ?2, 0, ?3, ?4, ?5, ?6, ?7, ?8, 0, 1, '{}', '{}')",
                rusqlite::params![
                    uuid,
                    row.git_commit,
                    row.hostname,
                    row.gate_name,
                    row.script,
                    row.fixture,
                    row.profile,
                    row.elapsed_ms
                ],
            )
            .unwrap();
    }

    #[test]
    fn insert_then_lookup_by_full_uuid() {
        let db = open_mem();
        let uuid = db.insert(&sample_row()).unwrap();
        let entry = db.lookup_baseline(&uuid, "host-a", "current").unwrap().unwrap();
        assert_eq!(entry.gate_name, "jmap_small");
        assert_eq!(entry.meta, r#"{"correct":1}"#);
    }

    #[test]
    fn lookup_by_prefix() {
        let db = open_mem();
        let uuid = db.insert(&sample_row()).unwrap();
        let prefix = &uuid[..8];
        let entry = db.lookup_baseline(prefix, "host-a", "current").unwrap().unwrap();
        assert_eq!(entry.uuid, uuid);
    }

    #[test]
    fn lookup_scoped_by_hostname() {
        let db = open_mem();
        let uuid = db.insert(&sample_row()).unwrap();
        // Same UUID, wrong host => not found.
        assert!(db.lookup_baseline(&uuid, "host-b", "current").unwrap().is_none());
    }

    #[test]
    fn empty_pin_is_refused() {
        let db = open_mem();
        db.insert(&sample_row()).unwrap();
        assert!(db.lookup_baseline("", "host-a", "current").is_err());
        assert!(db.lookup_baseline("ab cd", "host-a", "current").is_err());
        assert!(db.hosts_with_uuid("").is_err());
    }

    /// The run being evaluated is inserted before the lookup; a pin that
    /// prefixes it must never make it its own baseline.
    #[test]
    fn lookup_never_matches_the_current_run() {
        let db = open_mem();
        insert_with_uuid(&db, "aaaa1111");
        assert!(db.lookup_baseline("aaaa", "host-a", "aaaa1111").unwrap().is_none());
        assert!(db.lookup_baseline("aaaa1111", "host-a", "aaaa1111").unwrap().is_none());
        // With a real baseline beside it, the prefix resolves to that one.
        insert_with_uuid(&db, "aaaa2222");
        let entry = db.lookup_baseline("aaaa", "host-a", "aaaa1111").unwrap().unwrap();
        assert_eq!(entry.uuid, "aaaa2222");
    }

    #[test]
    fn ambiguous_prefix_is_refused() {
        let db = open_mem();
        insert_with_uuid(&db, "bbbb1111");
        insert_with_uuid(&db, "bbbb2222");
        let err = db.lookup_baseline("bbbb", "host-a", "current").unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("ambiguous"), "got: {msg}");
        assert!(msg.contains("bbbb1111") && msg.contains("bbbb2222"), "got: {msg}");
        // A longer pin disambiguates.
        let entry = db.lookup_baseline("bbbb2", "host-a", "current").unwrap().unwrap();
        assert_eq!(entry.uuid, "bbbb2222");
    }

    #[test]
    fn exact_match_wins_over_longer_prefixed_rows() {
        let db = open_mem();
        insert_with_uuid(&db, "cccc");
        insert_with_uuid(&db, "cccc9999");
        let entry = db.lookup_baseline("cccc", "host-a", "current").unwrap().unwrap();
        assert_eq!(entry.uuid, "cccc");
    }

    #[test]
    fn like_wildcards_are_literal() {
        let db = open_mem();
        insert_with_uuid(&db, "dddd1111");
        assert!(db.lookup_baseline("%", "host-a", "current").unwrap().is_none());
        assert!(db.lookup_baseline("d_dd", "host-a", "current").unwrap().is_none());
        assert!(db.hosts_with_uuid("%").unwrap().is_empty());
    }

    #[test]
    fn hosts_with_uuid_ignores_host_scope() {
        let db = open_mem();
        let uuid = db.insert(&sample_row()).unwrap();
        // The row is on host-a; asking from host-b's perspective, the
        // lookup fails but the UUID is still locatable.
        assert!(db.lookup_baseline(&uuid, "host-b", "current").unwrap().is_none());
        assert_eq!(db.hosts_with_uuid(&uuid).unwrap(), vec!["host-a"]);
        assert!(db.hosts_with_uuid("deadbeef").unwrap().is_empty());
    }

    #[test]
    fn count_for_gate_excludes_current_run() {
        let db = open_mem();
        let first = db.insert(&sample_row()).unwrap();
        let current = db.insert(&sample_row()).unwrap();
        assert_eq!(
            db.count_for_gate("jmap_small", "host-a", &current).unwrap(),
            1
        );
        assert_eq!(
            db.count_for_gate("jmap_small", "host-a", &first).unwrap(),
            1
        );
        assert_eq!(
            db.count_for_gate("other_gate", "host-a", &current).unwrap(),
            0
        );
    }

    #[test]
    fn lookup_missing_returns_none() {
        let db = open_mem();
        assert!(
            db.lookup_baseline("deadbeef", "host-a", "current")
                .unwrap()
                .is_none()
        );
    }
}
