//! Gate database for ratatoskr `sync-bench` regression gating.
//!
//! Per-project SQLite DB at `.brokkr/ratatoskr/gate.db` (committed,
//! same convention as `.brokkr/results.db`). One row per gated
//! `sync-bench` run. Baselines are pure pointers in `brokkr.toml`
//! (`[ratatoskr.gate.<name>.baseline].<hostname>`); they don't change
//! the write path.
//!
//! See `docs/commands/ratatoskr-gate.md` for the full design.

use std::path::Path;

use rusqlite::{Connection, OptionalExtension};

use super::types::generate_uuid;
use crate::error::DevError;

const SCHEMA_VERSION: i64 = 1;

const CREATE_TABLE: &str = "\
CREATE TABLE IF NOT EXISTS gate_runs (
    uuid          TEXT PRIMARY KEY,
    created_at    INTEGER NOT NULL,
    git_commit    TEXT NOT NULL,
    dirty         INTEGER NOT NULL,
    hostname      TEXT NOT NULL,
    gate_name     TEXT NOT NULL,
    script        TEXT NOT NULL,
    fixture       TEXT NOT NULL,
    profile       TEXT NOT NULL,
    elapsed_ms    INTEGER NOT NULL,
    exit_code     INTEGER NOT NULL,
    success       INTEGER NOT NULL,
    sidecar       TEXT NOT NULL,
    meta          TEXT NOT NULL
)";

const CREATE_INDEX: &str = "\
    CREATE INDEX IF NOT EXISTS idx_gate_runs_lookup \
    ON gate_runs(gate_name, hostname, created_at)";

pub struct GateDb {
    conn: Connection,
}

/// Row data for insertion. The `uuid` is generated by `insert`.
pub struct GateRow {
    pub git_commit: String,
    pub dirty: bool,
    pub hostname: String,
    pub gate_name: String,
    pub script: String,
    pub fixture: String,
    pub profile: String,
    pub elapsed_ms: i64,
    pub exit_code: i32,
    pub success: bool,
    /// JSON-serialized sidecar blob (object).
    pub sidecar: String,
    /// JSON-serialized meta blob (object). Mirrors `summary.json` ingestion.
    pub meta: String,
}

/// Row data returned from queries (full row including generated `uuid`
/// and `created_at`).
#[allow(dead_code)]
pub struct GateEntry {
    pub uuid: String,
    pub created_at: i64,
    pub git_commit: String,
    pub dirty: bool,
    pub hostname: String,
    pub gate_name: String,
    pub script: String,
    pub fixture: String,
    pub profile: String,
    pub elapsed_ms: i64,
    pub exit_code: i32,
    pub success: bool,
    pub sidecar: String,
    pub meta: String,
}

impl GateDb {
    /// Open (or create) the gate database at `path`.
    pub fn open(path: &Path) -> Result<Self, DevError> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let conn = Connection::open(path)?;
        conn.pragma_update(None, "journal_mode", "WAL")?;
        run_migrations(&conn)?;
        conn.execute_batch(CREATE_TABLE)?;
        conn.execute_batch(CREATE_INDEX)?;
        conn.pragma_update(None, "user_version", SCHEMA_VERSION)?;
        Ok(Self { conn })
    }

    /// Insert a row, returning its newly generated UUID.
    pub fn insert(&self, row: &GateRow) -> Result<String, DevError> {
        let uuid = generate_uuid()?;
        let created_at = unix_now();
        self.conn.execute(
            "INSERT INTO gate_runs (\
                uuid, created_at, git_commit, dirty, hostname, gate_name, \
                script, fixture, profile, elapsed_ms, exit_code, success, \
                sidecar, meta\
             ) VALUES (\
                ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14\
             )",
            rusqlite::params![
                uuid,
                created_at,
                row.git_commit,
                i64::from(row.dirty),
                row.hostname,
                row.gate_name,
                row.script,
                row.fixture,
                row.profile,
                row.elapsed_ms,
                row.exit_code,
                i64::from(row.success),
                row.sidecar,
                row.meta,
            ],
        )?;
        Ok(uuid)
    }

    /// Look up a baseline row by full-or-prefix UUID, scoped to the
    /// given hostname. Returns `Ok(None)` when no row matches.
    pub fn lookup_baseline(
        &self,
        uuid_prefix: &str,
        hostname: &str,
    ) -> Result<Option<GateEntry>, DevError> {
        let mut stmt = self.conn.prepare(
            "SELECT uuid, created_at, git_commit, dirty, hostname, gate_name, \
                    script, fixture, profile, elapsed_ms, exit_code, success, \
                    sidecar, meta \
             FROM gate_runs \
             WHERE uuid LIKE ?1 || '%' AND hostname = ?2 \
             ORDER BY created_at DESC LIMIT 1",
        )?;
        stmt.query_row(rusqlite::params![uuid_prefix, hostname], row_to_entry)
            .optional()
            .map_err(DevError::from)
    }
}

fn row_to_entry(row: &rusqlite::Row<'_>) -> rusqlite::Result<GateEntry> {
    Ok(GateEntry {
        uuid: row.get(0)?,
        created_at: row.get(1)?,
        git_commit: row.get(2)?,
        dirty: row.get::<_, i64>(3)? != 0,
        hostname: row.get(4)?,
        gate_name: row.get(5)?,
        script: row.get(6)?,
        fixture: row.get(7)?,
        profile: row.get(8)?,
        elapsed_ms: row.get(9)?,
        exit_code: row.get(10)?,
        success: row.get::<_, i64>(11)? != 0,
        sidecar: row.get(12)?,
        meta: row.get(13)?,
    })
}

fn unix_now() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| i64::try_from(d.as_secs()).unwrap_or(i64::MAX))
        .unwrap_or(0)
}

fn run_migrations(conn: &Connection) -> Result<(), DevError> {
    if !has_table(conn, "gate_runs") {
        return Ok(());
    }
    let current: i64 = conn.pragma_query_value(None, "user_version", |r| r.get(0))?;
    if current >= SCHEMA_VERSION {
        return Ok(());
    }
    // Future migrations go here.
    conn.pragma_update(None, "user_version", SCHEMA_VERSION)?;
    Ok(())
}

fn has_table(conn: &Connection, table: &str) -> bool {
    conn.query_row(
        "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=?1",
        [table],
        |row| row.get::<_, i64>(0),
    )
    .map(|count| count > 0)
    .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]
    use super::*;

    fn open_mem() -> GateDb {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(CREATE_TABLE).unwrap();
        conn.execute_batch(CREATE_INDEX).unwrap();
        conn.pragma_update(None, "user_version", SCHEMA_VERSION)
            .unwrap();
        GateDb { conn }
    }

    fn sample_row() -> GateRow {
        GateRow {
            git_commit: "abc123".into(),
            dirty: false,
            hostname: "host-a".into(),
            gate_name: "jmap_small".into(),
            script: "tests/sync/jmap.lua".into(),
            fixture: "jmap-init".into(),
            profile: "release".into(),
            elapsed_ms: 1234,
            exit_code: 0,
            success: true,
            sidecar: "{}".into(),
            meta: r#"{"correct":1}"#.into(),
        }
    }

    #[test]
    fn insert_then_lookup_by_full_uuid() {
        let db = open_mem();
        let uuid = db.insert(&sample_row()).unwrap();
        let entry = db.lookup_baseline(&uuid, "host-a").unwrap().unwrap();
        assert_eq!(entry.gate_name, "jmap_small");
        assert_eq!(entry.meta, r#"{"correct":1}"#);
    }

    #[test]
    fn lookup_by_prefix() {
        let db = open_mem();
        let uuid = db.insert(&sample_row()).unwrap();
        let prefix = &uuid[..8];
        let entry = db.lookup_baseline(prefix, "host-a").unwrap().unwrap();
        assert_eq!(entry.uuid, uuid);
    }

    #[test]
    fn lookup_scoped_by_hostname() {
        let db = open_mem();
        let uuid = db.insert(&sample_row()).unwrap();
        // Same UUID, wrong host => not found.
        assert!(db.lookup_baseline(&uuid, "host-b").unwrap().is_none());
    }

    #[test]
    fn lookup_missing_returns_none() {
        let db = open_mem();
        assert!(
            db.lookup_baseline("deadbeef", "host-a")
                .unwrap()
                .is_none()
        );
    }
}
