//! Insert operations for the results database.

use super::ResultsDb;
use super::schema::INSERT_SQL;
use super::types::{KvPair, KvValue, RunRow, generate_uuid, short_uuid};
use crate::error::DevError;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

impl ResultsDb {
    /// Insert a benchmark result row. Timestamp generated by SQLite
    /// `datetime('now')`. Returns the short UUID prefix (8 hex chars).
    pub fn insert(&self, row: &RunRow) -> Result<String, DevError> {
        let uuid = generate_uuid()?;
        self.conn.execute("BEGIN", [])?;

        let result = insert_inner(&self.conn, row, &uuid);
        if result.is_err() {
            self.conn.execute("ROLLBACK", []).ok();
            return result;
        }

        self.conn.execute("COMMIT", [])?;
        Ok(short_uuid(&uuid))
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn insert_inner(conn: &rusqlite::Connection, row: &RunRow, uuid: &str) -> Result<String, DevError> {
    // Envelope row.
    conn.execute(
        INSERT_SQL,
        rusqlite::params![
            row.hostname,
            row.commit,
            row.subject,
            row.command,
            row.variant,
            row.input_file,
            row.input_mb,
            row.elapsed_ms,
            row.peak_rss_mb,
            row.cargo_features,
            row.cargo_profile,
            row.kernel,
            row.cpu_governor,
            row.avail_memory_mb,
            row.storage_notes,
            uuid,
            row.cli_args,
            row.project,
        ],
    )?;
    let run_id = conn.last_insert_rowid();

    // Distribution child row.
    if let Some(ref dist) = row.distribution {
        conn.execute(
            "INSERT INTO run_distribution (run_id, samples, min_ms, p50_ms, p95_ms, max_ms) \
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            rusqlite::params![
                run_id,
                dist.samples,
                dist.min_ms,
                dist.p50_ms,
                dist.p95_ms,
                dist.max_ms
            ],
        )?;
    }

    // Key-value pairs.
    for kv in &row.kv {
        insert_kv_row(conn, run_id, kv)?;
    }

    // Hotpath child rows.
    if let Some(ref hp) = row.hotpath {
        for func in &hp.functions {
            conn.execute(
                "INSERT INTO hotpath_functions \
                 (run_id, section, description, ordinal, name, calls, avg, total, percent_total, p50, p95, p99) \
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)",
                rusqlite::params![
                    run_id, func.section, func.description, func.ordinal, func.name,
                    func.calls, func.avg, func.total, func.percent_total,
                    func.p50, func.p95, func.p99,
                ],
            )?;
        }
        for thread in &hp.threads {
            conn.execute(
                "INSERT INTO hotpath_threads \
                 (run_id, name, status, cpu_percent, cpu_percent_max, cpu_percent_avg, \
                  alloc_bytes, dealloc_bytes, mem_diff) \
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)",
                rusqlite::params![
                    run_id,
                    thread.name,
                    thread.status,
                    thread.cpu_percent,
                    thread.cpu_percent_max,
                    thread.cpu_percent_avg,
                    thread.alloc_bytes,
                    thread.dealloc_bytes,
                    thread.mem_diff,
                ],
            )?;
        }
        // Thread summary stats into run_kv.
        for kv in &hp.thread_summary {
            insert_kv_row(conn, run_id, kv)?;
        }
    }

    Ok(short_uuid(uuid))
}

fn insert_kv_row(conn: &rusqlite::Connection, run_id: i64, kv: &KvPair) -> Result<(), DevError> {
    // OR IGNORE: row.kv (stderr) is inserted first, thread_summary second.
    // Duplicates (same run_id+key) are silently skipped, keeping the stderr value.
    match &kv.value {
        KvValue::Int(v) => conn.execute(
            "INSERT OR IGNORE INTO run_kv (run_id, key, value_int) VALUES (?1, ?2, ?3)",
            rusqlite::params![run_id, kv.key, v],
        )?,
        KvValue::Real(v) => conn.execute(
            "INSERT OR IGNORE INTO run_kv (run_id, key, value_real) VALUES (?1, ?2, ?3)",
            rusqlite::params![run_id, kv.key, v],
        )?,
        KvValue::Text(v) => conn.execute(
            "INSERT OR IGNORE INTO run_kv (run_id, key, value_text) VALUES (?1, ?2, ?3)",
            rusqlite::params![run_id, kv.key, v],
        )?,
    };
    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use crate::db::{QueryFilter, ResultsDb, RunRow};

    #[test]
    fn db_open_and_insert_roundtrip() {
        let dir = std::env::temp_dir().join("brokkr_test_db_roundtrip");
        drop(std::fs::create_dir_all(&dir));
        let db_path = dir.join("test.db");
        // Clean up from previous runs.
        drop(std::fs::remove_file(&db_path));

        let db = ResultsDb::open(&db_path).expect("open db");
        let run = RunRow {
            hostname: String::from("testhost"),
            commit: String::from("aabbccdd"),
            subject: String::from("test subject"),
            command: String::from("read"),
            variant: Some(String::from("mmap")),
            input_file: Some(String::from("denmark.osm.pbf")),
            input_mb: Some(42.5),
            elapsed_ms: 1234,
            peak_rss_mb: None,
            cargo_features: None,
            cargo_profile: String::from("release"),
            kernel: None,
            cpu_governor: None,
            avail_memory_mb: None,
            storage_notes: None,
            cli_args: Some(String::from("--fast")),
            project: String::from("test"),
            kv: vec![],
            distribution: None,
            hotpath: None,
        };
        let short = db.insert(&run).expect("insert");
        assert_eq!(short.len(), 8, "short uuid should be 8 chars");

        let rows = db
            .query(&QueryFilter {
                commit: Some(String::from("aabbccdd")),
                command: None,
                variant: None,
                limit: 10,
            })
            .expect("query");
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].command, "read");
        assert_eq!(rows[0].variant, "mmap");
        assert_eq!(rows[0].input_file, "denmark.osm.pbf");
        assert_eq!(rows[0].elapsed_ms, 1234);
        assert_eq!(rows[0].cli_args, "--fast");

        // Clean up.
        drop(std::fs::remove_file(&db_path));
        drop(std::fs::remove_dir(&dir));
    }

    #[test]
    fn db_migrations_are_idempotent() {
        let dir = std::env::temp_dir().join("brokkr_test_db_migrations");
        drop(std::fs::create_dir_all(&dir));
        let db_path = dir.join("test.db");
        drop(std::fs::remove_file(&db_path));

        // Open twice -- second open should not fail on migrations.
        {
            let _db = ResultsDb::open(&db_path).expect("first open");
        }
        {
            let _db = ResultsDb::open(&db_path).expect("second open");
        }

        drop(std::fs::remove_file(&db_path));
        drop(std::fs::remove_dir(&dir));
    }
}
