//! Insert operations for the results database.

use super::ResultsDb;
use super::schema::INSERT_SQL;
use super::types::{KvPair, KvValue, RunRow, generate_uuid, short_uuid};
use crate::error::DevError;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

impl ResultsDb {
    /// Insert a benchmark result row. Timestamp generated by SQLite
    /// `datetime('now')`. Returns the short UUID prefix (8 hex chars).
    pub fn insert(&self, row: &RunRow) -> Result<String, DevError> {
        let (_, short) = self.insert_full(row)?;
        Ok(short)
    }

    /// Insert a benchmark result row, returning both the full UUID and the
    /// short prefix. Used when the full UUID is needed for linking (e.g.
    /// sidecar profile data).
    pub fn insert_full(&self, row: &RunRow) -> Result<(String, String), DevError> {
        let uuid = generate_uuid()?;
        self.conn.execute("BEGIN", [])?;

        let result = insert_inner(&self.conn, row, &uuid);
        if result.is_err() {
            self.conn.execute("ROLLBACK", []).ok();
            result?;
        }

        self.conn.execute("COMMIT", [])?;
        let short = short_uuid(&uuid);
        Ok((uuid, short))
    }

    /// Bulk-insert sidecar profile data for one benchmark run.
    ///
    /// Called after `insert_full` with the same UUID. Each run's sidecar
    /// data (samples, markers, summary) is inserted in a single transaction.
    pub fn store_sidecar_run(
        &self,
        result_uuid: &str,
        run_idx: usize,
        data: &crate::sidecar::SidecarData,
    ) -> Result<(), DevError> {
        let tx = self.conn.unchecked_transaction()?;

        // Insert samples.
        {
            let mut stmt = tx.prepare_cached(
                "INSERT INTO sidecar_samples (
                    result_uuid, run_idx, sample_idx, timestamp_us,
                    rss_kb, anon_kb, file_kb, shmem_kb, swap_kb, vsize_kb, vm_hwm_kb,
                    utime, stime, num_threads, minflt, majflt,
                    rchar, wchar, read_bytes, write_bytes, cancelled_write_bytes,
                    syscr, syscw, vol_cs, nonvol_cs
                ) VALUES (
                    ?1, ?2, ?3, ?4,
                    ?5, ?6, ?7, ?8, ?9, ?10, ?11,
                    ?12, ?13, ?14, ?15, ?16,
                    ?17, ?18, ?19, ?20, ?21,
                    ?22, ?23, ?24, ?25
                )",
            )?;

            for s in &data.samples {
                stmt.execute(rusqlite::params![
                    result_uuid,
                    run_idx as i64,
                    s.sample_idx,
                    s.timestamp_us,
                    s.rss_kb,
                    s.anon_kb,
                    s.file_kb,
                    s.shmem_kb,
                    s.swap_kb,
                    s.vsize_kb,
                    s.vm_hwm_kb,
                    s.utime,
                    s.stime,
                    s.num_threads,
                    s.minflt,
                    s.majflt,
                    s.rchar,
                    s.wchar,
                    s.read_bytes,
                    s.write_bytes,
                    s.cancelled_write_bytes,
                    s.syscr,
                    s.syscw,
                    s.vol_cs,
                    s.nonvol_cs,
                ])?;
            }
        }

        // Insert markers.
        {
            let mut stmt = tx.prepare_cached(
                "INSERT INTO sidecar_markers (
                    result_uuid, run_idx, marker_idx, timestamp_us, name
                ) VALUES (?1, ?2, ?3, ?4, ?5)",
            )?;

            for m in &data.markers {
                stmt.execute(rusqlite::params![
                    result_uuid,
                    run_idx as i64,
                    m.marker_idx,
                    m.timestamp_us,
                    m.name,
                ])?;
            }
        }

        // Insert summary.
        tx.execute(
            "INSERT INTO sidecar_summary (
                result_uuid, run_idx, vm_hwm_kb, sample_count, marker_count, wall_time_ms
            ) VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            rusqlite::params![
                result_uuid,
                run_idx as i64,
                data.summary.vm_hwm_kb,
                data.summary.sample_count,
                data.summary.marker_count,
                data.summary.wall_time_ms,
            ],
        )?;

        tx.commit()?;
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn insert_inner(conn: &rusqlite::Connection, row: &RunRow, uuid: &str) -> Result<String, DevError> {
    // Envelope row.
    conn.execute(
        INSERT_SQL,
        rusqlite::params![
            row.hostname,
            row.commit,
            row.subject,
            row.command,
            row.variant,
            row.input_file,
            row.input_mb,
            row.elapsed_ms,
            row.peak_rss_mb,
            row.cargo_features,
            row.cargo_profile,
            row.kernel,
            row.cpu_governor,
            row.avail_memory_mb,
            row.storage_notes,
            uuid,
            row.cli_args,
            row.project,
        ],
    )?;
    let run_id = conn.last_insert_rowid();

    // Distribution child row.
    if let Some(ref dist) = row.distribution {
        conn.execute(
            "INSERT INTO run_distribution (run_id, samples, min_ms, p50_ms, p95_ms, max_ms) \
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            rusqlite::params![
                run_id,
                dist.samples,
                dist.min_ms,
                dist.p50_ms,
                dist.p95_ms,
                dist.max_ms
            ],
        )?;
    }

    // Key-value pairs.
    for kv in &row.kv {
        insert_kv_row(conn, run_id, kv)?;
    }

    // Hotpath child rows.
    if let Some(ref hp) = row.hotpath {
        for func in &hp.functions {
            conn.execute(
                "INSERT INTO hotpath_functions \
                 (run_id, section, description, ordinal, name, calls, avg, total, percent_total, p50, p95, p99) \
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)",
                rusqlite::params![
                    run_id, func.section, func.description, func.ordinal, func.name,
                    func.calls, func.avg, func.total, func.percent_total,
                    func.p50, func.p95, func.p99,
                ],
            )?;
        }
        for thread in &hp.threads {
            conn.execute(
                "INSERT INTO hotpath_threads \
                 (run_id, name, status, cpu_percent, cpu_percent_max, cpu_percent_avg, \
                  alloc_bytes, dealloc_bytes, mem_diff) \
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)",
                rusqlite::params![
                    run_id,
                    thread.name,
                    thread.status,
                    thread.cpu_percent,
                    thread.cpu_percent_max,
                    thread.cpu_percent_avg,
                    thread.alloc_bytes,
                    thread.dealloc_bytes,
                    thread.mem_diff,
                ],
            )?;
        }
        // Thread summary stats into run_kv.
        for kv in &hp.thread_summary {
            insert_kv_row(conn, run_id, kv)?;
        }
    }

    Ok(short_uuid(uuid))
}

fn insert_kv_row(conn: &rusqlite::Connection, run_id: i64, kv: &KvPair) -> Result<(), DevError> {
    // OR IGNORE: row.kv (stderr) is inserted first, thread_summary second.
    // Duplicates (same run_id+key) are silently skipped, keeping the stderr value.
    match &kv.value {
        KvValue::Int(v) => conn.execute(
            "INSERT OR IGNORE INTO run_kv (run_id, key, value_int) VALUES (?1, ?2, ?3)",
            rusqlite::params![run_id, kv.key, v],
        )?,
        KvValue::Real(v) => conn.execute(
            "INSERT OR IGNORE INTO run_kv (run_id, key, value_real) VALUES (?1, ?2, ?3)",
            rusqlite::params![run_id, kv.key, v],
        )?,
        KvValue::Text(v) => conn.execute(
            "INSERT OR IGNORE INTO run_kv (run_id, key, value_text) VALUES (?1, ?2, ?3)",
            rusqlite::params![run_id, kv.key, v],
        )?,
    };
    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use crate::db::{QueryFilter, ResultsDb, RunRow};

    #[test]
    fn db_open_and_insert_roundtrip() {
        let dir = std::env::temp_dir().join("brokkr_test_db_roundtrip");
        drop(std::fs::create_dir_all(&dir));
        let db_path = dir.join("test.db");
        // Clean up from previous runs.
        drop(std::fs::remove_file(&db_path));

        let db = ResultsDb::open(&db_path).expect("open db");
        let run = RunRow {
            hostname: String::from("testhost"),
            commit: String::from("aabbccdd"),
            subject: String::from("test subject"),
            command: String::from("read"),
            variant: Some(String::from("mmap")),
            input_file: Some(String::from("denmark.osm.pbf")),
            input_mb: Some(42.5),
            elapsed_ms: 1234,
            peak_rss_mb: None,
            cargo_features: None,
            cargo_profile: String::from("release"),
            kernel: None,
            cpu_governor: None,
            avail_memory_mb: None,
            storage_notes: None,
            cli_args: Some(String::from("--fast")),
            project: String::from("test"),
            kv: vec![],
            distribution: None,
            hotpath: None,
        };
        let short = db.insert(&run).expect("insert");
        assert_eq!(short.len(), 8, "short uuid should be 8 chars");

        let rows = db
            .query(&QueryFilter {
                commit: Some(String::from("aabbccdd")),
                command: None,
                variant: None,
                limit: 10,
            })
            .expect("query");
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].command, "read");
        assert_eq!(rows[0].variant, "mmap");
        assert_eq!(rows[0].input_file, "denmark.osm.pbf");
        assert_eq!(rows[0].elapsed_ms, 1234);
        assert_eq!(rows[0].cli_args, "--fast");

        // Clean up.
        drop(std::fs::remove_file(&db_path));
        drop(std::fs::remove_dir(&dir));
    }

    #[test]
    fn db_migrations_are_idempotent() {
        let dir = std::env::temp_dir().join("brokkr_test_db_migrations");
        drop(std::fs::create_dir_all(&dir));
        let db_path = dir.join("test.db");
        drop(std::fs::remove_file(&db_path));

        // Open twice -- second open should not fail on migrations.
        {
            let _db = ResultsDb::open(&db_path).expect("first open");
        }
        {
            let _db = ResultsDb::open(&db_path).expect("second open");
        }

        drop(std::fs::remove_file(&db_path));
        drop(std::fs::remove_dir(&dir));
    }
}
