use std::io::Read;
use std::path::Path;

use crate::error::DevError;

/// Handle to the results database.
pub struct ResultsDb {
    conn: rusqlite::Connection,
}

/// A benchmark result row to insert.
pub struct RunRow {
    pub hostname: String,
    pub commit: String,
    pub subject: String,
    pub command: String,
    pub variant: Option<String>,
    pub input_file: Option<String>,
    pub input_mb: Option<f64>,
    pub elapsed_ms: i64,
    pub cargo_features: Option<String>,
    pub cargo_profile: String,
    pub kernel: Option<String>,
    pub cpu_governor: Option<String>,
    pub avail_memory_mb: Option<i64>,
    pub storage_notes: Option<String>,
    pub extra: Option<serde_json::Value>,
    pub cli_args: Option<String>,
    pub metadata: Option<serde_json::Value>,
}

/// A row read back from the database.
///
/// Nullable columns (`variant`, `input_file`, `cargo_features`, etc.) are
/// mapped to `String` via `unwrap_or_default()` — `NULL` becomes `""`.
/// This is intentional: all consumers use `.is_empty()` checks, so the
/// distinction between NULL and empty string is not needed.
#[allow(dead_code)]
pub struct StoredRow {
    pub id: i64,
    pub timestamp: String,
    pub hostname: String,
    pub commit: String,
    pub subject: String,
    pub command: String,
    pub variant: String,
    pub input_file: String,
    pub input_mb: Option<f64>,
    pub elapsed_ms: i64,
    pub cargo_features: String,
    pub cargo_profile: String,
    pub kernel: String,
    pub cpu_governor: String,
    pub avail_memory_mb: Option<i64>,
    pub storage_notes: String,
    pub extra: Option<serde_json::Value>,
    pub uuid: String,
    pub cli_args: String,
    pub metadata: Option<serde_json::Value>,
}

/// Two-commit comparison: (commit_a, rows_a, commit_b, rows_b).
pub type CompareResult = (String, Vec<StoredRow>, String, Vec<StoredRow>);

/// Filters for querying stored rows.
pub struct QueryFilter {
    pub commit: Option<String>,
    pub command: Option<String>,
    pub variant: Option<String>,
    pub limit: usize,
}

const SCHEMA: &str = "\
CREATE TABLE IF NOT EXISTS runs (
    id              INTEGER PRIMARY KEY,
    timestamp       TEXT NOT NULL,
    hostname        TEXT NOT NULL,
    [commit]        TEXT NOT NULL,
    subject         TEXT NOT NULL,
    command         TEXT NOT NULL,
    variant         TEXT,
    input_file      TEXT,
    input_mb        REAL,
    elapsed_ms      INTEGER NOT NULL,
    cargo_features  TEXT,
    cargo_profile   TEXT DEFAULT 'release',
    kernel          TEXT,
    cpu_governor    TEXT,
    avail_memory_mb INTEGER,
    storage_notes   TEXT,
    extra           TEXT,
    uuid            TEXT,
    cli_args        TEXT,
    metadata        TEXT
);
CREATE INDEX IF NOT EXISTS idx_runs_commit ON runs([commit]);
CREATE INDEX IF NOT EXISTS idx_runs_command ON runs(command);
CREATE INDEX IF NOT EXISTS idx_runs_timestamp ON runs(timestamp);
";

const SELECT_COLS: &str = "\
id, timestamp, hostname, [commit], subject, command, variant, \
input_file, input_mb, elapsed_ms, cargo_features, cargo_profile, \
kernel, cpu_governor, avail_memory_mb, storage_notes, extra, uuid, \
cli_args, metadata";

const INSERT_SQL: &str = "\
INSERT INTO runs (\
    timestamp, hostname, [commit], subject, command, variant, \
    input_file, input_mb, elapsed_ms, cargo_features, cargo_profile, \
    kernel, cpu_governor, avail_memory_mb, storage_notes, extra, uuid, \
    cli_args, metadata\
) VALUES (\
    datetime('now'), ?1, ?2, ?3, ?4, ?5, \
    ?6, ?7, ?8, ?9, ?10, \
    ?11, ?12, ?13, ?14, ?15, ?16, \
    ?17, ?18\
)";

impl ResultsDb {
    /// Open (or create) the database at `path`. Creates schema and enables WAL
    /// mode. Runs any pending migrations based on `PRAGMA user_version`.
    pub fn open(path: &Path) -> Result<Self, DevError> {
        let conn = rusqlite::Connection::open(path)?;
        conn.pragma_update(None, "journal_mode", "WAL")?;
        conn.execute_batch(SCHEMA)?;
        run_migrations(&conn)?;
        Ok(Self { conn })
    }

    /// Insert a benchmark result row. Timestamp generated by SQLite
    /// `datetime('now')`. Returns the short UUID prefix (8 hex chars).
    pub fn insert(&self, row: &RunRow) -> Result<String, DevError> {
        let extra_str = serialize_extra(&row.extra)?;
        let metadata_str = serialize_extra(&row.metadata)?;
        let uuid = generate_uuid()?;
        self.conn.execute(
            INSERT_SQL,
            rusqlite::params![
                row.hostname,
                row.commit,
                row.subject,
                row.command,
                row.variant,
                row.input_file,
                row.input_mb,
                row.elapsed_ms,
                row.cargo_features,
                row.cargo_profile,
                row.kernel,
                row.cpu_governor,
                row.avail_memory_mb,
                row.storage_notes,
                extra_str,
                uuid,
                row.cli_args,
                metadata_str,
            ],
        )?;
        Ok(short_uuid(&uuid))
    }

    /// Query rows by UUID prefix.
    pub fn query_by_uuid(&self, prefix: &str) -> Result<Vec<StoredRow>, DevError> {
        let sql = format!("SELECT {SELECT_COLS} FROM runs WHERE uuid LIKE ?1||'%' ORDER BY id DESC");
        let mut stmt = self.conn.prepare(&sql)?;
        let rows = stmt.query_map(rusqlite::params![prefix], map_stored_row)?;
        collect_rows(rows)
    }

    /// Query rows with optional filters. Commit matches by prefix (LIKE).
    /// Results ordered by id descending, limited to `filter.limit`.
    pub fn query(&self, filter: &QueryFilter) -> Result<Vec<StoredRow>, DevError> {
        let (sql, params) = build_query_sql(filter);
        let param_refs: Vec<&dyn rusqlite::types::ToSql> =
            params.iter().map(|p| p as &dyn rusqlite::types::ToSql).collect();
        let mut stmt = self.conn.prepare(&sql)?;
        let rows = stmt.query_map(param_refs.as_slice(), map_stored_row)?;
        collect_rows(rows)
    }

    /// Query two commits for side-by-side comparison. Each commit is matched
    /// by prefix. Optional command/variant filters narrow the results.
    pub fn query_compare(
        &self,
        a: &str,
        b: &str,
        command: Option<&str>,
        variant: Option<&str>,
    ) -> Result<(Vec<StoredRow>, Vec<StoredRow>), DevError> {
        let mut clauses = vec!["[commit] LIKE ?1||'%'".to_owned()];
        let mut params: Vec<String> = Vec::new();
        // ?1 is the commit, filled per-call below.
        params.push(String::new());
        if let Some(cmd) = command {
            params.push(cmd.to_owned());
            clauses.push(format!("command = ?{}", params.len()));
        }
        if let Some(v) = variant {
            params.push(v.to_owned());
            clauses.push(format!("variant LIKE ?{}||'%'", params.len()));
        }
        let sql = format!(
            "SELECT {SELECT_COLS} FROM runs WHERE {} ORDER BY command, variant, id DESC",
            clauses.join(" AND ")
        );
        let rows_a = query_commit_filtered(&self.conn, &sql, a, &params)?;
        let rows_b = query_commit_filtered(&self.conn, &sql, b, &params)?;
        Ok((rows_a, rows_b))
    }

    /// Find the two most recent distinct commits and compare them.
    /// Optional command/variant filters narrow the search (variant uses prefix match).
    pub fn query_compare_last(
        &self,
        command: Option<&str>,
        variant: Option<&str>,
    ) -> Result<Option<CompareResult>, DevError> {
        // Find two most recent distinct commits matching the filters.
        let mut clauses = Vec::new();
        let mut params: Vec<String> = Vec::new();
        if let Some(cmd) = command {
            params.push(cmd.to_owned());
            clauses.push(format!("command = ?{}", params.len()));
        }
        if let Some(v) = variant {
            params.push(v.to_owned());
            clauses.push(format!("variant LIKE ?{}||'%'", params.len()));
        }
        let mut sql = "SELECT DISTINCT [commit] FROM runs".to_owned();
        if !clauses.is_empty() {
            sql.push_str(" WHERE ");
            sql.push_str(&clauses.join(" AND "));
        }
        sql.push_str(" ORDER BY id DESC LIMIT 2");

        let param_refs: Vec<&dyn rusqlite::types::ToSql> =
            params.iter().map(|p| p as &dyn rusqlite::types::ToSql).collect();
        let mut stmt = self.conn.prepare(&sql)?;
        let commits: Vec<String> = stmt
            .query_map(param_refs.as_slice(), |row| row.get(0))?
            .filter_map(Result::ok)
            .collect();

        if commits.len() < 2 {
            return Ok(None);
        }

        let (rows_a, rows_b) = self.query_compare(&commits[1], &commits[0], command, variant)?;
        Ok(Some((commits[1].clone(), rows_a, commits[0].clone(), rows_b)))
    }
}

// ---------------------------------------------------------------------------
// Query helpers
// ---------------------------------------------------------------------------

fn query_commit_filtered(
    conn: &rusqlite::Connection,
    sql: &str,
    commit: &str,
    params: &[String],
) -> Result<Vec<StoredRow>, DevError> {
    let mut bound = params.to_vec();
    bound[0] = commit.to_owned();
    let param_refs: Vec<&dyn rusqlite::types::ToSql> =
        bound.iter().map(|p| p as &dyn rusqlite::types::ToSql).collect();
    let mut stmt = conn.prepare(sql)?;
    let rows = stmt.query_map(param_refs.as_slice(), map_stored_row)?;
    collect_rows(rows)
}

fn collect_rows(
    rows: rusqlite::MappedRows<'_, impl FnMut(&rusqlite::Row<'_>) -> rusqlite::Result<StoredRow>>,
) -> Result<Vec<StoredRow>, DevError> {
    let mut out = Vec::new();
    for row in rows {
        out.push(row?);
    }
    Ok(out)
}

fn map_stored_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<StoredRow> {
    let extra_raw: Option<String> = row.get("extra")?;
    let extra = match extra_raw {
        Some(s) => serde_json::from_str(&s).ok(),
        None => None,
    };
    Ok(StoredRow {
        id: row.get("id")?,
        timestamp: row.get("timestamp")?,
        hostname: row.get("hostname")?,
        commit: row.get("commit")?,
        subject: row.get("subject")?,
        command: row.get("command")?,
        variant: row.get::<_, Option<String>>("variant")?.unwrap_or_default(),
        input_file: row.get::<_, Option<String>>("input_file")?.unwrap_or_default(),
        input_mb: row.get("input_mb")?,
        elapsed_ms: row.get("elapsed_ms")?,
        cargo_features: row.get::<_, Option<String>>("cargo_features")?.unwrap_or_default(),
        cargo_profile: row.get::<_, Option<String>>("cargo_profile")?.unwrap_or_default(),
        kernel: row.get::<_, Option<String>>("kernel")?.unwrap_or_default(),
        cpu_governor: row.get::<_, Option<String>>("cpu_governor")?.unwrap_or_default(),
        avail_memory_mb: row.get("avail_memory_mb")?,
        storage_notes: row.get::<_, Option<String>>("storage_notes")?.unwrap_or_default(),
        extra,
        uuid: row.get::<_, Option<String>>("uuid")?.unwrap_or_default(),
        cli_args: row.get::<_, Option<String>>("cli_args")?.unwrap_or_default(),
        metadata: {
            let raw: Option<String> = row.get::<_, Option<String>>("metadata")?;
            match raw {
                Some(s) => serde_json::from_str(&s).ok(),
                None => None,
            }
        },
    })
}

fn serialize_extra(
    extra: &Option<serde_json::Value>,
) -> Result<Option<String>, DevError> {
    match extra {
        Some(val) => Ok(Some(serde_json::to_string(val)?)),
        None => Ok(None),
    }
}

fn build_query_sql(filter: &QueryFilter) -> (String, Vec<String>) {
    let mut clauses = Vec::new();
    let mut params: Vec<String> = Vec::new();

    if let Some(ref c) = filter.commit {
        params.push(c.clone());
        clauses.push(format!("[commit] LIKE ?{}||'%'", params.len()));
    }
    if let Some(ref cmd) = filter.command {
        params.push(cmd.clone());
        clauses.push(format!("command = ?{}", params.len()));
    }
    if let Some(ref v) = filter.variant {
        params.push(v.clone());
        clauses.push(format!("variant LIKE ?{}||'%'", params.len()));
    }

    let mut sql = format!("SELECT {SELECT_COLS} FROM runs");
    if !clauses.is_empty() {
        sql.push_str(" WHERE ");
        sql.push_str(&clauses.join(" AND "));
    }

    // Limit param is appended as the next positional parameter.
    params.push(filter.limit.to_string());
    sql.push_str(&format!(" ORDER BY id DESC LIMIT ?{}", params.len()));

    (sql, params)
}

// ---------------------------------------------------------------------------
// UUID
// ---------------------------------------------------------------------------

/// Generate a UUIDv4 as 32 hex chars (no dashes).
fn generate_uuid() -> Result<String, DevError> {
    let mut bytes = [0u8; 16];
    std::fs::File::open("/dev/urandom")?.read_exact(&mut bytes)?;
    // Set version 4.
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    // Set variant 1.
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    let hex: String = bytes.iter().map(|b| format!("{b:02x}")).collect();
    Ok(hex)
}

/// Return the first 8 hex chars of a UUID.
pub fn short_uuid(uuid: &str) -> String {
    uuid[..8.min(uuid.len())].to_owned()
}

/// Current schema version. Increment when adding new migrations.
const SCHEMA_VERSION: i64 = 2;

/// Run all pending migrations based on `PRAGMA user_version`.
fn run_migrations(conn: &rusqlite::Connection) -> Result<(), DevError> {
    let current: i64 = conn.pragma_query_value(None, "user_version", |row| row.get(0))?;

    if current >= SCHEMA_VERSION {
        return Ok(());
    }

    if current < 1 {
        migrate_uuid(conn)?;
    }
    if current < 2 {
        migrate_cli_args_metadata(conn)?;
    }

    conn.pragma_update(None, "user_version", SCHEMA_VERSION)?;
    Ok(())
}

/// Migration v0 -> v1: add uuid column and backfill.
fn migrate_uuid(conn: &rusqlite::Connection) -> Result<(), DevError> {
    let has_uuid = conn
        .prepare("PRAGMA table_info(runs)")?
        .query_map([], |row| row.get::<_, String>(1))?
        .any(|name| name.as_deref() == Ok("uuid"));

    if !has_uuid {
        conn.execute_batch("ALTER TABLE runs ADD COLUMN uuid TEXT")?;
    }

    // Backfill existing rows with generated UUIDs.
    let mut stmt = conn.prepare("SELECT id FROM runs WHERE uuid IS NULL")?;
    let ids: Vec<i64> = stmt
        .query_map([], |row| row.get(0))?
        .filter_map(Result::ok)
        .collect();

    let mut update = conn.prepare("UPDATE runs SET uuid = ?1 WHERE id = ?2")?;
    for id in ids {
        let uuid = generate_uuid()?;
        update.execute(rusqlite::params![uuid, id])?;
    }

    conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_runs_uuid ON runs(uuid)")?;
    Ok(())
}

/// Migration v1 -> v2: add cli_args and metadata columns.
fn migrate_cli_args_metadata(conn: &rusqlite::Connection) -> Result<(), DevError> {
    let has_cli_args = conn
        .prepare("PRAGMA table_info(runs)")?
        .query_map([], |row| row.get::<_, String>(1))?
        .any(|name| name.as_deref() == Ok("cli_args"));

    if !has_cli_args {
        conn.execute_batch("ALTER TABLE runs ADD COLUMN cli_args TEXT")?;
    }

    let has_metadata = conn
        .prepare("PRAGMA table_info(runs)")?
        .query_map([], |row| row.get::<_, String>(1))?
        .any(|name| name.as_deref() == Ok("metadata"));

    if !has_metadata {
        conn.execute_batch("ALTER TABLE runs ADD COLUMN metadata TEXT")?;
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Formatting
// ---------------------------------------------------------------------------

/// Format rows as a column-aligned table for stdout.
pub fn format_table(rows: &[StoredRow]) -> String {
    if rows.is_empty() {
        return String::from("(no results)");
    }

    let widths = compute_table_widths(rows);
    let mut out = String::new();

    // Header line.
    append_table_header(&mut out, &widths);
    out.push('\n');

    // Data lines.
    for row in rows {
        append_table_row(&mut out, row, &widths);
        out.push('\n');
    }

    // Remove trailing newline.
    if out.ends_with('\n') {
        out.pop();
    }
    out
}

/// Format the detail fields that aren't shown in the summary table.
///
/// Shows hostname, subject, cargo features/profile, kernel, cpu governor,
/// available memory, and storage notes — only when non-empty.
pub fn format_details(row: &StoredRow) -> String {
    let mut out = String::new();
    let mut fields: Vec<(&str, String)> = Vec::new();

    if !row.hostname.is_empty() {
        fields.push(("hostname", row.hostname.clone()));
    }
    if !row.subject.is_empty() {
        fields.push(("subject", row.subject.clone()));
    }
    if !row.cargo_features.is_empty() {
        fields.push(("cargo features", row.cargo_features.clone()));
    }
    if !row.cargo_profile.is_empty() {
        fields.push(("cargo profile", row.cargo_profile.clone()));
    }
    if !row.kernel.is_empty() {
        fields.push(("kernel", row.kernel.clone()));
    }
    if !row.cpu_governor.is_empty() {
        fields.push(("cpu governor", row.cpu_governor.clone()));
    }
    if let Some(mb) = row.avail_memory_mb {
        fields.push(("avail memory", format!("{mb} MB")));
    }
    if !row.storage_notes.is_empty() {
        fields.push(("storage", row.storage_notes.clone()));
    }
    if !row.cli_args.is_empty() {
        fields.push(("cli args", row.cli_args.clone()));
    }
    if let Some(ref meta) = row.metadata {
        fields.push(("metadata", serde_json::to_string_pretty(meta).unwrap_or_default()));
    }

    if fields.is_empty() {
        return out;
    }

    let label_width = fields.iter().map(|(l, _)| l.len()).max().unwrap_or(0);
    for (label, value) in &fields {
        use std::fmt::Write;
        writeln!(out, "  {label:<label_width$}  {value}").expect("write to String is infallible");
    }

    // Remove trailing newline.
    if out.ends_with('\n') {
        out.pop();
    }
    out
}

/// Format side-by-side comparison of two commits.
pub fn format_compare(
    commit_a: &str,
    rows_a: &[StoredRow],
    commit_b: &str,
    rows_b: &[StoredRow],
) -> String {
    let pairs = build_comparison_pairs(rows_a, rows_b);
    if pairs.is_empty() {
        return String::from("(no results)");
    }

    let widths = compute_compare_widths(commit_a, commit_b, &pairs);
    let mut out = String::new();

    append_compare_header(&mut out, commit_a, commit_b, &widths);
    out.push('\n');

    for pair in &pairs {
        append_compare_row(&mut out, pair, &widths);
        out.push('\n');
    }

    // Append hotpath diff tables for pairs that have extra data on both sides.
    for pair in &pairs {
        if let (Some(ea), Some(eb)) = (&pair.a_extra, &pair.b_extra)
            && let Some(diff) = crate::hotpath_fmt::format_hotpath_diff(ea, eb)
        {
            let (cmd, var, _) = split_pair_key(&pair.key);
            let heading = if pair.input_display.is_empty() {
                format!("\n{cmd} {var} — {commit_a} vs {commit_b}")
            } else {
                format!("\n{cmd} {var} - {} — {commit_a} vs {commit_b}", pair.input_display)
            };
            out.push_str(&heading);
            out.push('\n');
            out.push_str(&diff);
        }
    }

    if out.ends_with('\n') {
        out.pop();
    }
    out
}

// ---------------------------------------------------------------------------
// Table formatting internals
// ---------------------------------------------------------------------------

struct TableWidths {
    uuid: usize,
    timestamp: usize,
    commit: usize,
    command: usize,
    variant: usize,
    elapsed: usize,
    input: usize,
}

fn compute_table_widths(rows: &[StoredRow]) -> TableWidths {
    let mut w = TableWidths {
        uuid: 4,
        timestamp: 9,
        commit: 6,
        command: 7,
        variant: 7,
        elapsed: 7,
        input: 5,
    };
    for row in rows {
        let uuid_short = short_uuid(&row.uuid);
        if uuid_short.len() > w.uuid {
            w.uuid = uuid_short.len();
        }
        if row.timestamp.len() > w.timestamp {
            w.timestamp = row.timestamp.len();
        }
        if row.commit.len() > w.commit {
            w.commit = row.commit.len();
        }
        if row.command.len() > w.command {
            w.command = row.command.len();
        }
        if row.variant.len() > w.variant {
            w.variant = row.variant.len();
        }
        let elapsed_str = format_elapsed(row.elapsed_ms);
        if elapsed_str.len() > w.elapsed {
            w.elapsed = elapsed_str.len();
        }
        let input_str = format_input(&row.input_file, row.input_mb);
        if input_str.len() > w.input {
            w.input = input_str.len();
        }
    }
    w
}

fn append_table_header(out: &mut String, w: &TableWidths) {
    use std::fmt::Write;
    write!(
        out,
        "{:<uuid_w$}  {:<ts_w$}  {:<cm_w$}  {:<cmd_w$}  {:<var_w$}  {:>el_w$}  {:<in_w$}",
        "uuid",
        "timestamp",
        "commit",
        "command",
        "variant",
        "elapsed",
        "input",
        uuid_w = w.uuid,
        ts_w = w.timestamp,
        cm_w = w.commit,
        cmd_w = w.command,
        var_w = w.variant,
        el_w = w.elapsed,
        in_w = w.input,
    )
    .expect("write to String is infallible");
}

fn append_table_row(out: &mut String, row: &StoredRow, w: &TableWidths) {
    use std::fmt::Write;
    let uuid_short = short_uuid(&row.uuid);
    let elapsed_str = format_elapsed(row.elapsed_ms);
    let input_str = format_input(&row.input_file, row.input_mb);
    write!(
        out,
        "{:<uuid_w$}  {:<ts_w$}  {:<cm_w$}  {:<cmd_w$}  {:<var_w$}  {:>el_w$}  {:<in_w$}",
        uuid_short,
        row.timestamp,
        row.commit,
        row.command,
        row.variant,
        elapsed_str,
        input_str,
        uuid_w = w.uuid,
        ts_w = w.timestamp,
        cm_w = w.commit,
        cmd_w = w.command,
        var_w = w.variant,
        el_w = w.elapsed,
        in_w = w.input,
    )
    .expect("write to String is infallible");
}

fn format_elapsed(ms: i64) -> String {
    format!("{ms} ms")
}

fn format_input(input_file: &str, input_mb: Option<f64>) -> String {
    if input_file.is_empty() {
        return String::new();
    }
    let basename = Path::new(input_file)
        .file_stem()
        .map_or(input_file, |s| s.to_str().unwrap_or(input_file));
    match input_mb {
        Some(mb) => format!("{basename} ({mb:.0} MB)"),
        None => basename.to_owned(),
    }
}

// ---------------------------------------------------------------------------
// Compare formatting internals
// ---------------------------------------------------------------------------

struct CompareWidths {
    command: usize,
    variant: usize,
    input: usize,
    col_a: usize,
    col_b: usize,
    change: usize,
}

struct ComparisonPair {
    key: String,
    a_ms: Option<i64>,
    b_ms: Option<i64>,
    a_extra: Option<serde_json::Value>,
    b_extra: Option<serde_json::Value>,
    /// Pre-formatted input string for display.
    input_display: String,
}

fn build_comparison_pairs(
    rows_a: &[StoredRow],
    rows_b: &[StoredRow],
) -> Vec<ComparisonPair> {
    use std::collections::HashMap;

    struct RowData {
        elapsed_ms: i64,
        extra: Option<serde_json::Value>,
        input_display: String,
    }

    let mut keys: Vec<String> = Vec::new();
    let mut a_map: HashMap<String, RowData> = HashMap::new();
    let mut b_map: HashMap<String, RowData> = HashMap::new();

    for row in rows_a {
        let key = pair_key(&row.command, &row.variant, &row.input_file);
        if let std::collections::hash_map::Entry::Vacant(e) = a_map.entry(key.clone()) {
            keys.push(key);
            e.insert(RowData {
                elapsed_ms: row.elapsed_ms,
                extra: row.extra.clone(),
                input_display: format_input(&row.input_file, row.input_mb),
            });
        }
    }
    for row in rows_b {
        let key = pair_key(&row.command, &row.variant, &row.input_file);
        if let std::collections::hash_map::Entry::Vacant(e) = b_map.entry(key.clone()) {
            if !a_map.contains_key(&key) {
                keys.push(key.clone());
            }
            e.insert(RowData {
                elapsed_ms: row.elapsed_ms,
                extra: row.extra.clone(),
                input_display: format_input(&row.input_file, row.input_mb),
            });
        }
    }

    keys.into_iter()
        .map(|k| {
            let a = a_map.remove(&k);
            let b = b_map.remove(&k);
            let input_display = a.as_ref().or(b.as_ref())
                .map(|r| r.input_display.clone())
                .unwrap_or_default();
            ComparisonPair {
                key: k,
                a_ms: a.as_ref().map(|r| r.elapsed_ms),
                b_ms: b.as_ref().map(|r| r.elapsed_ms),
                a_extra: a.and_then(|r| r.extra),
                b_extra: b.and_then(|r| r.extra),
                input_display,
            }
        })
        .collect()
}

fn pair_key(command: &str, variant: &str, input_file: &str) -> String {
    format!("{command}\t{variant}\t{input_file}")
}

fn split_pair_key(key: &str) -> (&str, &str, &str) {
    let mut parts = key.splitn(3, '\t');
    let cmd = parts.next().unwrap_or("");
    let var = parts.next().unwrap_or("");
    let input = parts.next().unwrap_or("");
    (cmd, var, input)
}

fn compute_compare_widths(
    commit_a: &str,
    commit_b: &str,
    pairs: &[ComparisonPair],
) -> CompareWidths {
    let mut w = CompareWidths {
        command: 7,
        variant: 7,
        input: 5,
        col_a: commit_a.len().max(2),
        col_b: commit_b.len().max(2),
        change: 6,
    };
    for pair in pairs {
        let (cmd, var, _) = split_pair_key(&pair.key);
        w.command = w.command.max(cmd.len());
        w.variant = w.variant.max(var.len());
        w.input = w.input.max(pair.input_display.len());
        w.col_a = w.col_a.max(format_ms_or_dash(pair.a_ms).len());
        w.col_b = w.col_b.max(format_ms_or_dash(pair.b_ms).len());
        w.change = w.change.max(format_change(pair.a_ms, pair.b_ms).len());
    }
    w
}

fn append_compare_header(
    out: &mut String,
    commit_a: &str,
    commit_b: &str,
    w: &CompareWidths,
) {
    use std::fmt::Write;
    write!(
        out,
        "{:<cmd_w$}  {:<var_w$}  {:<in_w$}  {:>a_w$}  {:>b_w$}  {:>ch_w$}",
        "command",
        "variant",
        "input",
        commit_a,
        commit_b,
        "change",
        cmd_w = w.command,
        var_w = w.variant,
        in_w = w.input,
        a_w = w.col_a,
        b_w = w.col_b,
        ch_w = w.change,
    )
    .expect("write to String is infallible");
}

fn append_compare_row(
    out: &mut String,
    pair: &ComparisonPair,
    w: &CompareWidths,
) {
    use std::fmt::Write;
    let (cmd, var, _) = split_pair_key(&pair.key);
    let a_str = format_ms_or_dash(pair.a_ms);
    let b_str = format_ms_or_dash(pair.b_ms);
    let ch = format_change(pair.a_ms, pair.b_ms);
    write!(
        out,
        "{:<cmd_w$}  {:<var_w$}  {:<in_w$}  {:>a_w$}  {:>b_w$}  {:>ch_w$}",
        cmd,
        var,
        pair.input_display,
        a_str,
        b_str,
        ch,
        cmd_w = w.command,
        var_w = w.variant,
        in_w = w.input,
        a_w = w.col_a,
        b_w = w.col_b,
        ch_w = w.change,
    )
    .expect("write to String is infallible");
}

fn format_ms_or_dash(ms: Option<i64>) -> String {
    match ms {
        Some(v) => format!("{v} ms"),
        None => String::from("--"),
    }
}

fn format_change(a_ms: Option<i64>, b_ms: Option<i64>) -> String {
    match (a_ms, b_ms) {
        (Some(a), Some(b)) if a != 0 => {
            #[allow(clippy::cast_precision_loss)]
            let pct = ((b - a) as f64 / a as f64) * 100.0;
            if pct >= 0.0 {
                format!("+{pct:.1}%")
            } else {
                format!("{pct:.1}%")
            }
        }
        _ => String::from("--"),
    }
}
