use std::io::Read;
use std::path::Path;

use crate::error::DevError;

/// Handle to the results database.
pub struct ResultsDb {
    conn: rusqlite::Connection,
}

/// A benchmark result row to insert.
pub struct RunRow {
    pub hostname: String,
    pub commit: String,
    pub subject: String,
    pub command: String,
    pub variant: Option<String>,
    pub input_file: Option<String>,
    pub input_mb: Option<f64>,
    pub elapsed_ms: i64,
    pub cargo_features: Option<String>,
    pub cargo_profile: String,
    pub kernel: Option<String>,
    pub cpu_governor: Option<String>,
    pub avail_memory_mb: Option<i64>,
    pub storage_notes: Option<String>,
    pub extra: Option<serde_json::Value>,
}

/// A row read back from the database.
#[allow(dead_code)]
pub struct StoredRow {
    pub id: i64,
    pub timestamp: String,
    pub hostname: String,
    pub commit: String,
    pub subject: String,
    pub command: String,
    pub variant: String,
    pub input_file: String,
    pub input_mb: Option<f64>,
    pub elapsed_ms: i64,
    pub cargo_features: String,
    pub cargo_profile: String,
    pub kernel: String,
    pub cpu_governor: String,
    pub avail_memory_mb: Option<i64>,
    pub storage_notes: String,
    pub extra: Option<serde_json::Value>,
    pub uuid: String,
}

/// Filters for querying stored rows.
pub struct QueryFilter {
    pub commit: Option<String>,
    pub command: Option<String>,
    pub variant: Option<String>,
    pub limit: usize,
}

const SCHEMA: &str = "\
CREATE TABLE IF NOT EXISTS runs (
    id              INTEGER PRIMARY KEY,
    timestamp       TEXT NOT NULL,
    hostname        TEXT NOT NULL,
    [commit]        TEXT NOT NULL,
    subject         TEXT NOT NULL,
    command         TEXT NOT NULL,
    variant         TEXT,
    input_file      TEXT,
    input_mb        REAL,
    elapsed_ms      INTEGER NOT NULL,
    cargo_features  TEXT,
    cargo_profile   TEXT DEFAULT 'release',
    kernel          TEXT,
    cpu_governor    TEXT,
    avail_memory_mb INTEGER,
    storage_notes   TEXT,
    extra           TEXT,
    uuid            TEXT
);
CREATE INDEX IF NOT EXISTS idx_runs_commit ON runs([commit]);
CREATE INDEX IF NOT EXISTS idx_runs_command ON runs(command);
CREATE INDEX IF NOT EXISTS idx_runs_timestamp ON runs(timestamp);
CREATE INDEX IF NOT EXISTS idx_runs_uuid ON runs(uuid);
";

const INSERT_SQL: &str = "\
INSERT INTO runs (\
    timestamp, hostname, [commit], subject, command, variant, \
    input_file, input_mb, elapsed_ms, cargo_features, cargo_profile, \
    kernel, cpu_governor, avail_memory_mb, storage_notes, extra, uuid\
) VALUES (\
    datetime('now'), ?1, ?2, ?3, ?4, ?5, \
    ?6, ?7, ?8, ?9, ?10, \
    ?11, ?12, ?13, ?14, ?15, ?16\
)";

impl ResultsDb {
    /// Open (or create) the database at `path`. Creates schema and enables WAL
    /// mode. Migrates existing databases to add the uuid column.
    pub fn open(path: &Path) -> Result<Self, DevError> {
        let conn = rusqlite::Connection::open(path)?;
        conn.pragma_update(None, "journal_mode", "WAL")?;
        conn.execute_batch(SCHEMA)?;
        migrate_uuid(&conn)?;
        Ok(Self { conn })
    }

    /// Insert a benchmark result row. Timestamp generated by SQLite
    /// `datetime('now')`. Returns the short UUID prefix (8 hex chars).
    pub fn insert(&self, row: &RunRow) -> Result<String, DevError> {
        let extra_str = serialize_extra(&row.extra)?;
        let uuid = generate_uuid()?;
        self.conn.execute(
            INSERT_SQL,
            rusqlite::params![
                row.hostname,
                row.commit,
                row.subject,
                row.command,
                row.variant,
                row.input_file,
                row.input_mb,
                row.elapsed_ms,
                row.cargo_features,
                row.cargo_profile,
                row.kernel,
                row.cpu_governor,
                row.avail_memory_mb,
                row.storage_notes,
                extra_str,
                uuid,
            ],
        )?;
        Ok(short_uuid(&uuid))
    }

    /// Query rows by UUID prefix.
    pub fn query_by_uuid(&self, prefix: &str) -> Result<Vec<StoredRow>, DevError> {
        let sql = "SELECT * FROM runs WHERE uuid LIKE ?1||'%' ORDER BY id DESC";
        let mut stmt = self.conn.prepare(sql)?;
        let rows = stmt.query_map(rusqlite::params![prefix], map_stored_row)?;
        collect_rows(rows)
    }

    /// Query rows with optional filters. Commit matches by prefix (LIKE).
    /// Results ordered by id descending, limited to `filter.limit`.
    pub fn query(&self, filter: &QueryFilter) -> Result<Vec<StoredRow>, DevError> {
        let (sql, params) = build_query_sql(filter);
        let param_refs: Vec<&dyn rusqlite::types::ToSql> =
            params.iter().map(|p| p as &dyn rusqlite::types::ToSql).collect();
        let mut stmt = self.conn.prepare(&sql)?;
        let rows = stmt.query_map(param_refs.as_slice(), map_stored_row)?;
        collect_rows(rows)
    }

    /// Query two commits for side-by-side comparison. Each commit is matched
    /// by prefix.
    pub fn query_compare(
        &self,
        a: &str,
        b: &str,
    ) -> Result<(Vec<StoredRow>, Vec<StoredRow>), DevError> {
        let sql = "SELECT * FROM runs WHERE [commit] LIKE ?1||'%' \
                   ORDER BY command, variant";
        let rows_a = query_commit(&self.conn, sql, a)?;
        let rows_b = query_commit(&self.conn, sql, b)?;
        Ok((rows_a, rows_b))
    }
}

// ---------------------------------------------------------------------------
// Query helpers
// ---------------------------------------------------------------------------

fn query_commit(
    conn: &rusqlite::Connection,
    sql: &str,
    commit: &str,
) -> Result<Vec<StoredRow>, DevError> {
    let mut stmt = conn.prepare(sql)?;
    let rows = stmt.query_map(rusqlite::params![commit], map_stored_row)?;
    collect_rows(rows)
}

fn collect_rows(
    rows: rusqlite::MappedRows<'_, impl FnMut(&rusqlite::Row<'_>) -> rusqlite::Result<StoredRow>>,
) -> Result<Vec<StoredRow>, DevError> {
    let mut out = Vec::new();
    for row in rows {
        out.push(row?);
    }
    Ok(out)
}

fn map_stored_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<StoredRow> {
    let extra_raw: Option<String> = row.get(16)?;
    let extra = match extra_raw {
        Some(s) => serde_json::from_str(&s).ok(),
        None => None,
    };
    Ok(StoredRow {
        id: row.get(0)?,
        timestamp: row.get(1)?,
        hostname: row.get(2)?,
        commit: row.get(3)?,
        subject: row.get(4)?,
        command: row.get(5)?,
        variant: row.get::<_, Option<String>>(6)?.unwrap_or_default(),
        input_file: row.get::<_, Option<String>>(7)?.unwrap_or_default(),
        input_mb: row.get(8)?,
        elapsed_ms: row.get(9)?,
        cargo_features: row.get::<_, Option<String>>(10)?.unwrap_or_default(),
        cargo_profile: row.get::<_, Option<String>>(11)?.unwrap_or_default(),
        kernel: row.get::<_, Option<String>>(12)?.unwrap_or_default(),
        cpu_governor: row.get::<_, Option<String>>(13)?.unwrap_or_default(),
        avail_memory_mb: row.get(14)?,
        storage_notes: row.get::<_, Option<String>>(15)?.unwrap_or_default(),
        extra,
        uuid: row.get::<_, Option<String>>(17)?.unwrap_or_default(),
    })
}

fn serialize_extra(
    extra: &Option<serde_json::Value>,
) -> Result<Option<String>, DevError> {
    match extra {
        Some(val) => Ok(Some(serde_json::to_string(val)?)),
        None => Ok(None),
    }
}

fn build_query_sql(filter: &QueryFilter) -> (String, Vec<String>) {
    let mut clauses = Vec::new();
    let mut params: Vec<String> = Vec::new();

    if let Some(ref c) = filter.commit {
        params.push(c.clone());
        clauses.push(format!("[commit] LIKE ?{}||'%'", params.len()));
    }
    if let Some(ref cmd) = filter.command {
        params.push(cmd.clone());
        clauses.push(format!("command = ?{}", params.len()));
    }
    if let Some(ref v) = filter.variant {
        params.push(v.clone());
        clauses.push(format!("variant = ?{}", params.len()));
    }

    let mut sql = String::from("SELECT * FROM runs");
    if !clauses.is_empty() {
        sql.push_str(" WHERE ");
        sql.push_str(&clauses.join(" AND "));
    }

    // Limit param is appended as the next positional parameter.
    params.push(filter.limit.to_string());
    sql.push_str(&format!(" ORDER BY id DESC LIMIT ?{}", params.len()));

    (sql, params)
}

// ---------------------------------------------------------------------------
// UUID
// ---------------------------------------------------------------------------

/// Generate a UUIDv4 as 32 hex chars (no dashes).
fn generate_uuid() -> Result<String, DevError> {
    let mut bytes = [0u8; 16];
    std::fs::File::open("/dev/urandom")?.read_exact(&mut bytes)?;
    // Set version 4.
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    // Set variant 1.
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    let hex: String = bytes.iter().map(|b| format!("{b:02x}")).collect();
    Ok(hex)
}

/// Return the first 8 hex chars of a UUID.
pub fn short_uuid(uuid: &str) -> String {
    uuid[..8.min(uuid.len())].to_owned()
}

/// Migrate existing databases: add uuid column and backfill.
fn migrate_uuid(conn: &rusqlite::Connection) -> Result<(), DevError> {
    let has_uuid = conn
        .prepare("PRAGMA table_info(runs)")?
        .query_map([], |row| row.get::<_, String>(1))?
        .any(|name| name.as_deref() == Ok("uuid"));

    if has_uuid {
        return Ok(());
    }

    conn.execute_batch("ALTER TABLE runs ADD COLUMN uuid TEXT")?;

    // Backfill existing rows with generated UUIDs.
    let mut stmt = conn.prepare("SELECT id FROM runs WHERE uuid IS NULL")?;
    let ids: Vec<i64> = stmt
        .query_map([], |row| row.get(0))?
        .filter_map(Result::ok)
        .collect();

    let mut update = conn.prepare("UPDATE runs SET uuid = ?1 WHERE id = ?2")?;
    for id in ids {
        let uuid = generate_uuid()?;
        update.execute(rusqlite::params![uuid, id])?;
    }

    conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_runs_uuid ON runs(uuid)")?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Formatting
// ---------------------------------------------------------------------------

/// Format rows as a column-aligned table for stdout.
pub fn format_table(rows: &[StoredRow]) -> String {
    if rows.is_empty() {
        return String::from("(no results)");
    }

    let widths = compute_table_widths(rows);
    let mut out = String::new();

    // Header line.
    append_table_header(&mut out, &widths);
    out.push('\n');

    // Data lines.
    for row in rows {
        append_table_row(&mut out, row, &widths);
        out.push('\n');
    }

    // Remove trailing newline.
    if out.ends_with('\n') {
        out.pop();
    }
    out
}

/// Format the detail fields that aren't shown in the summary table.
///
/// Shows hostname, subject, cargo features/profile, kernel, cpu governor,
/// available memory, and storage notes — only when non-empty.
pub fn format_details(row: &StoredRow) -> String {
    let mut out = String::new();
    let mut fields: Vec<(&str, String)> = Vec::new();

    if !row.hostname.is_empty() {
        fields.push(("hostname", row.hostname.clone()));
    }
    if !row.subject.is_empty() {
        fields.push(("subject", row.subject.clone()));
    }
    if !row.cargo_features.is_empty() {
        fields.push(("cargo features", row.cargo_features.clone()));
    }
    if !row.cargo_profile.is_empty() {
        fields.push(("cargo profile", row.cargo_profile.clone()));
    }
    if !row.kernel.is_empty() {
        fields.push(("kernel", row.kernel.clone()));
    }
    if !row.cpu_governor.is_empty() {
        fields.push(("cpu governor", row.cpu_governor.clone()));
    }
    if let Some(mb) = row.avail_memory_mb {
        fields.push(("avail memory", format!("{mb} MB")));
    }
    if !row.storage_notes.is_empty() {
        fields.push(("storage", row.storage_notes.clone()));
    }

    if fields.is_empty() {
        return out;
    }

    let label_width = fields.iter().map(|(l, _)| l.len()).max().unwrap_or(0);
    for (label, value) in &fields {
        use std::fmt::Write;
        writeln!(out, "  {label:<label_width$}  {value}").expect("write to String is infallible");
    }

    // Remove trailing newline.
    if out.ends_with('\n') {
        out.pop();
    }
    out
}

/// Format side-by-side comparison of two commits.
pub fn format_compare(
    commit_a: &str,
    rows_a: &[StoredRow],
    commit_b: &str,
    rows_b: &[StoredRow],
) -> String {
    let pairs = build_comparison_pairs(rows_a, rows_b);
    if pairs.is_empty() {
        return String::from("(no results)");
    }

    let widths = compute_compare_widths(commit_a, commit_b, &pairs);
    let mut out = String::new();

    append_compare_header(&mut out, commit_a, commit_b, &widths);
    out.push('\n');

    for (key, a_ms, b_ms) in &pairs {
        append_compare_row(&mut out, key, *a_ms, *b_ms, &widths);
        out.push('\n');
    }

    if out.ends_with('\n') {
        out.pop();
    }
    out
}

// ---------------------------------------------------------------------------
// Table formatting internals
// ---------------------------------------------------------------------------

struct TableWidths {
    uuid: usize,
    timestamp: usize,
    commit: usize,
    command: usize,
    variant: usize,
    elapsed: usize,
    input: usize,
}

fn compute_table_widths(rows: &[StoredRow]) -> TableWidths {
    let mut w = TableWidths {
        uuid: 4,
        timestamp: 9,
        commit: 6,
        command: 7,
        variant: 7,
        elapsed: 7,
        input: 5,
    };
    for row in rows {
        let uuid_short = short_uuid(&row.uuid);
        if uuid_short.len() > w.uuid {
            w.uuid = uuid_short.len();
        }
        if row.timestamp.len() > w.timestamp {
            w.timestamp = row.timestamp.len();
        }
        if row.commit.len() > w.commit {
            w.commit = row.commit.len();
        }
        if row.command.len() > w.command {
            w.command = row.command.len();
        }
        if row.variant.len() > w.variant {
            w.variant = row.variant.len();
        }
        let elapsed_str = format_elapsed(row.elapsed_ms);
        if elapsed_str.len() > w.elapsed {
            w.elapsed = elapsed_str.len();
        }
        let input_str = format_input(&row.input_file, row.input_mb);
        if input_str.len() > w.input {
            w.input = input_str.len();
        }
    }
    w
}

fn append_table_header(out: &mut String, w: &TableWidths) {
    use std::fmt::Write;
    write!(
        out,
        "{:<uuid_w$}  {:<ts_w$}  {:<cm_w$}  {:<cmd_w$}  {:<var_w$}  {:>el_w$}  {:<in_w$}",
        "uuid",
        "timestamp",
        "commit",
        "command",
        "variant",
        "elapsed",
        "input",
        uuid_w = w.uuid,
        ts_w = w.timestamp,
        cm_w = w.commit,
        cmd_w = w.command,
        var_w = w.variant,
        el_w = w.elapsed,
        in_w = w.input,
    )
    .expect("write to String is infallible");
}

fn append_table_row(out: &mut String, row: &StoredRow, w: &TableWidths) {
    use std::fmt::Write;
    let uuid_short = short_uuid(&row.uuid);
    let elapsed_str = format_elapsed(row.elapsed_ms);
    let input_str = format_input(&row.input_file, row.input_mb);
    write!(
        out,
        "{:<uuid_w$}  {:<ts_w$}  {:<cm_w$}  {:<cmd_w$}  {:<var_w$}  {:>el_w$}  {:<in_w$}",
        uuid_short,
        row.timestamp,
        row.commit,
        row.command,
        row.variant,
        elapsed_str,
        input_str,
        uuid_w = w.uuid,
        ts_w = w.timestamp,
        cm_w = w.commit,
        cmd_w = w.command,
        var_w = w.variant,
        el_w = w.elapsed,
        in_w = w.input,
    )
    .expect("write to String is infallible");
}

fn format_elapsed(ms: i64) -> String {
    format!("{ms} ms")
}

fn format_input(input_file: &str, input_mb: Option<f64>) -> String {
    if input_file.is_empty() {
        return String::new();
    }
    let basename = Path::new(input_file)
        .file_stem()
        .map_or(input_file, |s| s.to_str().unwrap_or(input_file));
    match input_mb {
        Some(mb) => format!("{basename} ({mb:.0} MB)"),
        None => basename.to_owned(),
    }
}

// ---------------------------------------------------------------------------
// Compare formatting internals
// ---------------------------------------------------------------------------

struct CompareWidths {
    command: usize,
    variant: usize,
    col_a: usize,
    col_b: usize,
    change: usize,
}

/// (command_variant_key, a_elapsed_ms or None, b_elapsed_ms or None)
type ComparisonPair = (String, Option<i64>, Option<i64>);

fn build_comparison_pairs(
    rows_a: &[StoredRow],
    rows_b: &[StoredRow],
) -> Vec<ComparisonPair> {
    // Use a Vec to preserve insertion order.
    let mut keys: Vec<String> = Vec::new();
    let mut a_map: std::collections::HashMap<String, i64> =
        std::collections::HashMap::new();
    let mut b_map: std::collections::HashMap<String, i64> =
        std::collections::HashMap::new();

    for row in rows_a {
        let key = pair_key(&row.command, &row.variant);
        if !a_map.contains_key(&key) {
            keys.push(key.clone());
        }
        a_map.insert(key, row.elapsed_ms);
    }
    for row in rows_b {
        let key = pair_key(&row.command, &row.variant);
        if !a_map.contains_key(&key) && !b_map.contains_key(&key) {
            keys.push(key.clone());
        }
        b_map.insert(key, row.elapsed_ms);
    }

    keys.into_iter()
        .map(|k| {
            let a_ms = a_map.get(&k).copied();
            let b_ms = b_map.get(&k).copied();
            (k, a_ms, b_ms)
        })
        .collect()
}

fn pair_key(command: &str, variant: &str) -> String {
    if variant.is_empty() {
        command.to_owned()
    } else {
        format!("{command}\t{variant}")
    }
}

fn split_pair_key(key: &str) -> (&str, &str) {
    match key.find('\t') {
        Some(pos) => (&key[..pos], &key[pos + 1..]),
        None => (key, ""),
    }
}

fn compute_compare_widths(
    commit_a: &str,
    commit_b: &str,
    pairs: &[ComparisonPair],
) -> CompareWidths {
    let mut w = CompareWidths {
        command: 7,
        variant: 7,
        col_a: commit_a.len().max(2),
        col_b: commit_b.len().max(2),
        change: 6,
    };
    for (key, a_ms, b_ms) in pairs {
        let (cmd, var) = split_pair_key(key);
        if cmd.len() > w.command {
            w.command = cmd.len();
        }
        if var.len() > w.variant {
            w.variant = var.len();
        }
        let a_str = format_ms_or_dash(*a_ms);
        if a_str.len() > w.col_a {
            w.col_a = a_str.len();
        }
        let b_str = format_ms_or_dash(*b_ms);
        if b_str.len() > w.col_b {
            w.col_b = b_str.len();
        }
        let ch = format_change(*a_ms, *b_ms);
        if ch.len() > w.change {
            w.change = ch.len();
        }
    }
    w
}

fn append_compare_header(
    out: &mut String,
    commit_a: &str,
    commit_b: &str,
    w: &CompareWidths,
) {
    use std::fmt::Write;
    write!(
        out,
        "{:<cmd_w$}  {:<var_w$}  {:>a_w$}  {:>b_w$}  {:>ch_w$}",
        "command",
        "variant",
        commit_a,
        commit_b,
        "change",
        cmd_w = w.command,
        var_w = w.variant,
        a_w = w.col_a,
        b_w = w.col_b,
        ch_w = w.change,
    )
    .expect("write to String is infallible");
}

fn append_compare_row(
    out: &mut String,
    key: &str,
    a_ms: Option<i64>,
    b_ms: Option<i64>,
    w: &CompareWidths,
) {
    use std::fmt::Write;
    let (cmd, var) = split_pair_key(key);
    let a_str = format_ms_or_dash(a_ms);
    let b_str = format_ms_or_dash(b_ms);
    let ch = format_change(a_ms, b_ms);
    write!(
        out,
        "{:<cmd_w$}  {:<var_w$}  {:>a_w$}  {:>b_w$}  {:>ch_w$}",
        cmd,
        var,
        a_str,
        b_str,
        ch,
        cmd_w = w.command,
        var_w = w.variant,
        a_w = w.col_a,
        b_w = w.col_b,
        ch_w = w.change,
    )
    .expect("write to String is infallible");
}

fn format_ms_or_dash(ms: Option<i64>) -> String {
    match ms {
        Some(v) => format!("{v} ms"),
        None => String::from("--"),
    }
}

fn format_change(a_ms: Option<i64>, b_ms: Option<i64>) -> String {
    match (a_ms, b_ms) {
        (Some(a), Some(b)) if a != 0 => {
            #[allow(clippy::cast_precision_loss)]
            let pct = ((b - a) as f64 / a as f64) * 100.0;
            if pct >= 0.0 {
                format!("+{pct:.1}%")
            } else {
                format!("{pct:.1}%")
            }
        }
        _ => String::from("--"),
    }
}
