mod artefacts;
mod bench_cmd;
mod build;
mod cargo_filter;
mod cargo_json;
mod check_cmd;
mod cli;
mod config;
mod context;
mod db;
mod dellingr;
mod mogwai;
mod dependency_rules;
mod deps;
mod elivagar;
mod env;
mod error;
mod git;
mod globs;
mod gremlins;
mod header;
mod harness;
mod history;
mod history_cmd;
mod hotpath_fmt;
mod invalidate_cmd;
mod litehtml;
mod lex;
mod lockfile;
mod man;
mod manifest;
mod measure;
mod nidhogg;
mod oom;
mod osc;
mod output;
mod pbfhogg;
mod piners;
mod pmtiles;
mod preflight;
mod profile;
mod project;
mod ratatoskr;
mod request;
mod resolve;
mod results_cmd;
mod runnables;
mod rustflags;
mod scope;
mod script_check;
mod shutdown;
mod sidecar;
mod sidecar_cmd;
mod sidecar_fmt;
mod sluggrs;
mod test_cmd;
mod textlint;
mod cpu_topology;
mod test_runner;
#[cfg(test)]
mod test_scratch;
mod toolchain;
mod tools;
mod wc;
mod worktree;
mod worktree_record;

use std::path::Path;
use std::process;
use std::time::{Duration, Instant};

use clap::Parser;

use cli::{Cli, Command, VerifyCommand};
use context::{acquire_cmd_lock, acquire_cmd_lock_opt, bootstrap, bootstrap_config, with_worktree};
use error::DevError;
use project::Project;
use request::{CorpusQuery, ResultsQuery, SidecarQuery};

include!("main_parts/bootstrap.rs");
include!("main_parts/commands.rs");
