/// Query parameters for the results command.
pub(crate) struct ResultsQuery {
    pub(crate) query: Option<String>,
    pub(crate) commit: Option<String>,
    pub(crate) compare: Option<Vec<String>>,
    pub(crate) compare_last: bool,
    pub(crate) command: Option<String>,
    pub(crate) variant: Option<String>,
    pub(crate) limit: usize,
    pub(crate) top: usize,
    pub(crate) timeline: bool,
    pub(crate) markers: bool,
    pub(crate) summary: bool,
    pub(crate) durations: bool,
    pub(crate) fields: Vec<String>,
    pub(crate) every: Option<usize>,
    pub(crate) head: Option<usize>,
    pub(crate) tail: Option<usize>,
    pub(crate) where_cond: Option<String>,
    pub(crate) stat: Option<String>,
    pub(crate) phase: Option<String>,
    pub(crate) range: Option<String>,
}
