//! Benchmark: run pbfhogg CLI commands and measure wall-clock time.

use std::path::{Path, PathBuf};

use crate::error::DevError;
use crate::harness::{BenchConfig, BenchHarness};
use crate::output;

pub const ALL_COMMANDS: &[&str] = &[
    "inspect",
    "inspect-nodes",
    "inspect-tags",
    "inspect-tags-way",
    "check-refs",
    "check-ids",
    "sort",
    "cat",
    "cat-way",
    "cat-relation",
    "cat-dedupe",
    "tags-filter-way",
    "tags-filter-amenity",
    "tags-filter-twopass",
    "tags-filter-osc",
    "getid",
    "getparents",
    "getid-invert",
    "renumber",
    "merge-changes",
    "apply-changes",
    "add-locations-to-ways",
    "extract-simple",
    "extract-complete",
    "extract-smart",
    "time-filter",
    "diff",
    "diff-osc",
];

/// Map a suite preset name to the consolidated brokkr command name.
///
/// The suite keeps its per-preset iteration names (e.g. `cat-way`,
/// `cat-relation`, `cat-dedupe`) so each row stays distinct in the DB,
/// but the `command` column writes the consolidated spelling
/// (e.g. `cat`) so queries line up with the user-facing subcommand
/// shape. Unlisted presets pass through unchanged.
fn consolidated_command_name(preset: &str) -> &str {
    match preset {
        "cat-way" | "cat-relation" | "cat-dedupe" => "cat",
        "extract-simple" | "extract-complete" | "extract-smart" => "extract",
        "tags-filter-way"
        | "tags-filter-amenity"
        | "tags-filter-twopass"
        | "tags-filter-osc" => "tags-filter",
        "getid-refs" | "getid-invert" => "getid",
        "inspect-nodes" | "inspect-tags" | "inspect-tags-way" => "inspect",
        "diff-osc" => "diff",
        other => other,
    }
}

/// Commands that need a second PBF (generated by merging base + OSC).
const NEEDS_MERGED: &[&str] = &["diff", "diff-osc"];

/// Commands that directly need an OSC file as input.
const NEEDS_OSC: &[&str] = &["tags-filter-osc", "merge-changes", "apply-changes"];

/// Commands that produce `.osc.gz` output instead of `.osm.pbf`.
const OSC_OUTPUT: &[&str] = &["tags-filter-osc", "merge-changes", "diff-osc"];

/// Commands that produce no output file (no `-o` flag). Everything else writes to scratch.
const NO_OUTPUT_FILE: &[&str] = &[
    "inspect",
    "inspect-nodes",
    "inspect-tags",
    "inspect-tags-way",
    "check-refs",
    "check-ids",
    "diff",
];

#[allow(clippy::too_many_lines)]
fn command_args(
    name: &str,
    pbf: &str,
    merged_pbf: Option<&str>,
    osc: Option<&str>,
    output: &str,
    index_type: Option<&str>,
) -> Result<Vec<String>, DevError> {
    let args = match name {
        "inspect" => vec!["inspect".into(), pbf.into()],
        "inspect-nodes" => vec!["inspect".into(), "--nodes".into(), pbf.into()],
        "inspect-tags" => vec![
            "inspect".into(),
            "tags".into(),
            pbf.into(),
            "--min-count".into(),
            "999999999".into(),
        ],
        "inspect-tags-way" => vec![
            "inspect".into(),
            "tags".into(),
            pbf.into(),
            "--type".into(),
            "way".into(),
            "--min-count".into(),
            "999999999".into(),
        ],
        "check-refs" => vec!["check".into(), "--refs".into(), pbf.into()],
        "check-ids" => vec!["check".into(), "--ids".into(), pbf.into()],
        "sort" => vec!["sort".into(), pbf.into(), "-o".into(), output.into()],
        "cat" => vec!["cat".into(), pbf.into(), "-o".into(), output.into()],
        "cat-way" => vec![
            "cat".into(),
            pbf.into(),
            "--type".into(),
            "way".into(),
            "-o".into(),
            output.into(),
        ],
        "cat-relation" => vec![
            "cat".into(),
            pbf.into(),
            "--type".into(),
            "relation".into(),
            "-o".into(),
            output.into(),
        ],
        "cat-dedupe" => vec![
            "cat".into(),
            "--dedupe".into(),
            pbf.into(),
            pbf.into(),
            "-o".into(),
            output.into(),
        ],
        "tags-filter-way" => vec![
            "tags-filter".into(),
            pbf.into(),
            "-R".into(),
            "w/highway=primary".into(),
            "-o".into(),
            output.into(),
        ],
        "tags-filter-amenity" => vec![
            "tags-filter".into(),
            pbf.into(),
            "-R".into(),
            "amenity=restaurant".into(),
            "-o".into(),
            output.into(),
        ],
        "tags-filter-twopass" => vec![
            "tags-filter".into(),
            pbf.into(),
            "highway=primary".into(),
            "-o".into(),
            output.into(),
        ],
        "tags-filter-osc" => {
            let o =
                osc.ok_or_else(|| DevError::Config("tags-filter-osc requires an OSC file".into()))?;
            vec![
                "tags-filter".into(),
                "--input-kind".into(),
                "osc".into(),
                o.into(),
                "highway=primary".into(),
                "-o".into(),
                output.into(),
            ]
        }
        "getid" => vec![
            "getid".into(),
            pbf.into(),
            "n115722".into(),
            "n115723".into(),
            "n115724".into(),
            "w2080".into(),
            "w2081".into(),
            "w2082".into(),
            "r174".into(),
            "r213".into(),
            "r339".into(),
            "-o".into(),
            output.into(),
        ],
        "getparents" => vec![
            "getparents".into(),
            pbf.into(),
            "n115722".into(),
            "n115723".into(),
            "w2080".into(),
            "-o".into(),
            output.into(),
        ],
        "getid-invert" => vec![
            "getid".into(),
            "--invert".into(),
            pbf.into(),
            "n115722".into(),
            "n115723".into(),
            "n115724".into(),
            "w2080".into(),
            "w2081".into(),
            "w2082".into(),
            "r174".into(),
            "r213".into(),
            "r339".into(),
            "-o".into(),
            output.into(),
        ],
        "renumber" => vec!["renumber".into(), pbf.into(), "-o".into(), output.into()],
        "merge-changes" => {
            let o =
                osc.ok_or_else(|| DevError::Config("merge-changes requires an OSC file".into()))?;
            vec!["merge-changes".into(), o.into(), "-o".into(), output.into()]
        }
        "apply-changes" => {
            let o =
                osc.ok_or_else(|| DevError::Config("apply-changes requires an OSC file".into()))?;
            vec![
                "apply-changes".into(),
                pbf.into(),
                o.into(),
                "-o".into(),
                output.into(),
            ]
        }
        "add-locations-to-ways" => {
            let mut args = vec![
                "add-locations-to-ways".into(),
                pbf.into(),
                "-o".into(),
                output.into(),
            ];
            if let Some(it) = index_type {
                args.push("--index-type".into());
                args.push(it.into());
            }
            args
        }
        "extract-simple" => vec![
            "extract".into(),
            pbf.into(),
            "--simple".into(),
            "-b".into(),
            "12.4,55.6,12.7,55.8".into(),
            "-o".into(),
            output.into(),
        ],
        "extract-complete" => vec![
            "extract".into(),
            pbf.into(),
            "-b".into(),
            "12.4,55.6,12.7,55.8".into(),
            "-o".into(),
            output.into(),
        ],
        "extract-smart" => vec![
            "extract".into(),
            pbf.into(),
            "--smart".into(),
            "-b".into(),
            "12.4,55.6,12.7,55.8".into(),
            "-o".into(),
            output.into(),
        ],
        "time-filter" => vec![
            "time-filter".into(),
            pbf.into(),
            "2024-01-01T00:00:00Z".into(),
            "-o".into(),
            output.into(),
        ],
        "diff" => {
            let m =
                merged_pbf.ok_or_else(|| DevError::Config("diff requires merged PBF".into()))?;
            vec!["diff".into(), pbf.into(), m.into(), "-c".into()]
        }
        "diff-osc" => {
            let m = merged_pbf
                .ok_or_else(|| DevError::Config("diff-osc requires merged PBF".into()))?;
            vec![
                "diff".into(),
                "--format".into(),
                "osc".into(),
                pbf.into(),
                m.into(),
                "-o".into(),
                output.into(),
            ]
        }
        _ => unreachable!("unknown command: {name}"),
    };
    Ok(args)
}

/// Check whether any of the requested commands need a merged PBF.
fn needs_merged_pbf(commands: &[&str]) -> bool {
    commands.iter().any(|c| NEEDS_MERGED.contains(c))
}

/// Check whether any of the requested commands directly need an OSC file.
fn needs_osc(commands: &[&str]) -> bool {
    commands.iter().any(|c| NEEDS_OSC.contains(c))
}

/// Ensure a merged PBF exists in the scratch directory. Returns the path.
/// Skips merge if the file already exists.
fn ensure_merged_pbf(
    binary: &Path,
    pbf_path: &Path,
    osc_path: &Path,
    scratch_dir: &Path,
    project_root: &Path,
) -> Result<PathBuf, DevError> {
    let stem = pbf_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("input");
    let merged_name = format!("{stem}-bench-merged.osm.pbf");
    let merged_path = scratch_dir.join(&merged_name);

    if merged_path.exists() {
        output::bench_msg(&format!("using cached merged PBF: {merged_name}"));
        return Ok(merged_path);
    }

    std::fs::create_dir_all(scratch_dir)
        .map_err(|e| DevError::Config(format!("failed to create scratch dir: {e}")))?;

    output::bench_msg(&format!("generating merged PBF: {merged_name}"));
    let pbf_str = pbf_path
        .to_str()
        .ok_or_else(|| DevError::Config("PBF path not UTF-8".into()))?;
    let osc_str = osc_path
        .to_str()
        .ok_or_else(|| DevError::Config("OSC path not UTF-8".into()))?;
    let merged_str = merged_path
        .to_str()
        .ok_or_else(|| DevError::Config("merged path not UTF-8".into()))?;
    let binary_str = binary.display().to_string();

    let captured = output::run_captured(
        &binary_str,
        &["apply-changes", pbf_str, osc_str, "-o", merged_str],
        project_root,
    )?;

    captured.check_success(&binary_str)?;

    Ok(merged_path)
}

#[allow(clippy::too_many_arguments)]
pub fn run(
    harness: &BenchHarness,
    binary: &Path,
    pbf_path: &Path,
    osc_path: Option<&Path>,
    scratch_dir: Option<&Path>,
    file_mb: f64,
    runs: usize,
    commands: &[&str],
    project_root: &Path,
    index_type: Option<&str>,
) -> Result<(), DevError> {
    let (basename, pbf_str) = super::path_strs(pbf_path)?;

    // Resolve OSC path string for commands that directly need it.
    let osc_str = if needs_osc(commands) {
        let osc = osc_path.ok_or_else(|| {
            DevError::Config("tags-filter-osc/merge-changes/apply-changes require an OSC file (dataset must have osc configured)".into())
        })?;
        Some(
            osc.to_str()
                .ok_or_else(|| DevError::Config("OSC path not UTF-8".into()))?
                .to_owned(),
        )
    } else {
        None
    };

    // Generate merged PBF if any requested command needs it.
    let merged_pbf = if needs_merged_pbf(commands) {
        let osc = osc_path.ok_or_else(|| {
            DevError::Config(
                "diff/diff-osc require an OSC file (dataset must have osc configured)".into(),
            )
        })?;
        let scratch = scratch_dir
            .ok_or_else(|| DevError::Config("diff/diff-osc require a scratch directory".into()))?;
        Some(ensure_merged_pbf(
            binary,
            pbf_path,
            osc,
            scratch,
            project_root,
        )?)
    } else {
        None
    };
    let merged_str = merged_pbf.as_ref().and_then(|p| p.to_str());

    // Ensure scratch dir exists for commands that write output files.
    let has_output_commands = commands.iter().any(|c| !NO_OUTPUT_FILE.contains(c));
    if has_output_commands && let Some(sd) = scratch_dir {
        std::fs::create_dir_all(sd)
            .map_err(|e| DevError::Config(format!("failed to create scratch dir: {e}")))?;
    }

    crate::harness::run_variants("command", commands, |name| {
        // Commands that produce output files write to scratch; others have no -o flag.
        let scratch_output_path = if !NO_OUTPUT_FILE.contains(&name) {
            let ext = if OSC_OUTPUT.contains(&name) {
                "osc.gz"
            } else {
                "osm.pbf"
            };
            scratch_dir.map(|sd| sd.join(format!("bench-{name}-output.{ext}")))
        } else {
            None
        };
        let output_str = match scratch_output_path.as_ref().and_then(|p| p.to_str()) {
            Some(s) => s.to_owned(),
            None if NO_OUTPUT_FILE.contains(&name) => String::new(),
            None => {
                return Err(DevError::Config(format!(
                    "command '{name}' produces output but no scratch directory is configured"
                )));
            }
        };

        let args = command_args(
            name,
            pbf_str,
            merged_str,
            osc_str.as_deref(),
            &output_str,
            index_type,
        )?;
        let args_refs: Vec<&str> = args.iter().map(String::as_str).collect();

        let config = BenchConfig {
            command: consolidated_command_name(name).into(),
            // Index type (for add-locations-to-ways) is in cli_args
            // via --index-type. Measurement mode and brokkr_args come
            // from the harness.
            mode: None,
            input_file: Some(basename.clone()),
            input_mb: Some(file_mb),
            cargo_features: None,
            cargo_profile: "release".into(),
            runs,
            cli_args: Some(crate::harness::format_cli_args(
                &binary.display().to_string(),
                &args_refs,
            )),
            brokkr_args: None,
            metadata: vec![],
        };

        harness.run_external(&config, binary, &args_refs, project_root)?;

        // Clean up scratch output file.
        if let Some(ref path) = scratch_output_path {
            std::fs::remove_file(path).ok();
        }
        Ok(())
    })
}
