//! Benchmark: run pbfhogg CLI commands and measure wall-clock time.

use std::path::{Path, PathBuf};

use crate::error::DevError;
use crate::harness::{BenchConfig, BenchHarness};
use crate::output;

pub const ALL_COMMANDS: &[&str] = &[
    "fileinfo",
    "check-refs",
    "sort",
    "cat-way",
    "cat-relation",
    "tags-count",
    "tags-count-way",
    "tags-filter-way",
    "tags-filter-amenity",
    "tags-filter-twopass",
    "getid",
    "removeid",
    "add-locations-to-ways",
    "extract-simple",
    "extract-complete",
    "extract-smart",
    "node-stats",
    "diff",
    "derive-changes",
];

/// Commands that need a second PBF (generated by merging base + OSC).
const NEEDS_MERGED: &[&str] = &["diff", "derive-changes"];

pub fn parse_command(input: &str) -> Result<Vec<&'static str>, DevError> {
    if input == "all" {
        return Ok(ALL_COMMANDS.to_vec());
    }
    // Exact match first.
    for &cmd in ALL_COMMANDS {
        if cmd == input {
            return Ok(vec![cmd]);
        }
    }
    // Prefix match: e.g. "tags-filter" matches all "tags-filter-*" variants.
    let prefix_matches: Vec<&str> = ALL_COMMANDS
        .iter()
        .copied()
        .filter(|cmd| cmd.starts_with(input))
        .collect();
    if !prefix_matches.is_empty() {
        return Ok(prefix_matches);
    }
    Err(DevError::Config(format!(
        "unknown command: {input}\nvalid commands: all, {}",
        ALL_COMMANDS.join(", ")
    )))
}

fn command_args(name: &str, pbf: &str, merged_pbf: Option<&str>) -> Result<Vec<String>, DevError> {
    let args = match name {
        "fileinfo" => vec!["fileinfo".into(), "--extended".into(), pbf.into()],
        "check-refs" => vec!["check-refs".into(), pbf.into()],
        "sort" => vec!["sort".into(), pbf.into(), "-o".into(), "/dev/null".into()],
        "cat-way" => vec!["cat".into(), pbf.into(), "--type".into(), "way".into(), "-o".into(), "/dev/null".into()],
        "cat-relation" => vec!["cat".into(), pbf.into(), "--type".into(), "relation".into(), "-o".into(), "/dev/null".into()],
        "tags-count" => vec!["tags-count".into(), pbf.into(), "--min-count".into(), "999999999".into()],
        "tags-count-way" => vec!["tags-count".into(), pbf.into(), "--type".into(), "way".into(), "--min-count".into(), "999999999".into()],
        "tags-filter-way" => vec!["tags-filter".into(), pbf.into(), "-R".into(), "w/highway=primary".into(), "-o".into(), "/dev/null".into()],
        "tags-filter-amenity" => vec!["tags-filter".into(), pbf.into(), "-R".into(), "amenity=restaurant".into(), "-o".into(), "/dev/null".into()],
        "tags-filter-twopass" => vec!["tags-filter".into(), pbf.into(), "highway=primary".into(), "-o".into(), "/dev/null".into()],
        "getid" => vec!["getid".into(), pbf.into(), "n115722".into(), "n115723".into(), "n115724".into(), "w2080".into(), "w2081".into(), "w2082".into(), "r174".into(), "r213".into(), "r339".into(), "-o".into(), "/dev/null".into()],
        "removeid" => vec!["removeid".into(), pbf.into(), "n115722".into(), "n115723".into(), "n115724".into(), "w2080".into(), "w2081".into(), "w2082".into(), "r174".into(), "r213".into(), "r339".into(), "-o".into(), "/dev/null".into()],
        "add-locations-to-ways" => vec!["add-locations-to-ways".into(), pbf.into(), "-o".into(), "/dev/null".into()],
        "extract-simple" => vec!["extract".into(), pbf.into(), "--simple".into(), "-b".into(), "12.4,55.6,12.7,55.8".into(), "-o".into(), "/dev/null".into()],
        "extract-complete" => vec!["extract".into(), pbf.into(), "-b".into(), "12.4,55.6,12.7,55.8".into(), "-o".into(), "/dev/null".into()],
        "extract-smart" => vec!["extract".into(), pbf.into(), "--smart".into(), "-b".into(), "12.4,55.6,12.7,55.8".into(), "-o".into(), "/dev/null".into()],
        "node-stats" => vec!["node-stats".into(), pbf.into()],
        "diff" => {
            let m = merged_pbf.ok_or_else(|| DevError::Config("diff requires merged PBF".into()))?;
            vec!["diff".into(), pbf.into(), m.into(), "-c".into()]
        }
        "derive-changes" => {
            let m = merged_pbf.ok_or_else(|| DevError::Config("derive-changes requires merged PBF".into()))?;
            vec!["derive-changes".into(), pbf.into(), m.into(), "-o".into(), "/dev/null".into()]
        }
        _ => unreachable!("unknown command: {name}"),
    };
    Ok(args)
}

/// Check whether any of the requested commands need a merged PBF.
fn needs_merged_pbf(commands: &[&str]) -> bool {
    commands.iter().any(|c| NEEDS_MERGED.contains(c))
}

/// Ensure a merged PBF exists in the scratch directory. Returns the path.
/// Skips merge if the file already exists.
fn ensure_merged_pbf(
    binary: &Path,
    pbf_path: &Path,
    osc_path: &Path,
    scratch_dir: &Path,
    project_root: &Path,
) -> Result<PathBuf, DevError> {
    let stem = pbf_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("input");
    let merged_name = format!("{stem}-bench-merged.osm.pbf");
    let merged_path = scratch_dir.join(&merged_name);

    if merged_path.exists() {
        output::bench_msg(&format!("using cached merged PBF: {merged_name}"));
        return Ok(merged_path);
    }

    std::fs::create_dir_all(scratch_dir).map_err(|e| {
        DevError::Config(format!("failed to create scratch dir: {e}"))
    })?;

    output::bench_msg(&format!("generating merged PBF: {merged_name}"));
    let pbf_str = pbf_path.to_str().ok_or_else(|| DevError::Config("PBF path not UTF-8".into()))?;
    let osc_str = osc_path.to_str().ok_or_else(|| DevError::Config("OSC path not UTF-8".into()))?;
    let merged_str = merged_path.to_str().ok_or_else(|| DevError::Config("merged path not UTF-8".into()))?;
    let binary_str = binary.display().to_string();

    let captured = output::run_captured(
        &binary_str,
        &["merge", pbf_str, osc_str, "-o", merged_str],
        project_root,
    )?;

    if !captured.status.success() {
        let stderr = String::from_utf8_lossy(&captured.stderr);
        return Err(DevError::Subprocess {
            program: binary_str,
            code: captured.status.code(),
            stderr: stderr.into_owned(),
        });
    }

    Ok(merged_path)
}

#[allow(clippy::too_many_arguments)]
pub fn run(
    harness: &BenchHarness,
    binary: &Path,
    pbf_path: &Path,
    osc_path: Option<&Path>,
    scratch_dir: Option<&Path>,
    file_mb: f64,
    runs: usize,
    commands: &[&str],
    project_root: &Path,
) -> Result<(), DevError> {
    let (basename, pbf_str) = super::path_strs(pbf_path)?;

    // Generate merged PBF if any requested command needs it.
    let merged_pbf = if needs_merged_pbf(commands) {
        let osc = osc_path.ok_or_else(|| {
            DevError::Config("diff/derive-changes require an OSC file (dataset must have osc configured)".into())
        })?;
        let scratch = scratch_dir.ok_or_else(|| {
            DevError::Config("diff/derive-changes require a scratch directory".into())
        })?;
        Some(ensure_merged_pbf(binary, pbf_path, osc, scratch, project_root)?)
    } else {
        None
    };
    let merged_str = merged_pbf.as_ref().and_then(|p| p.to_str());

    for &name in commands {
        output::bench_msg(&format!("command: {name}"));
        let args = command_args(name, pbf_str, merged_str)?;
        let args_refs: Vec<&str> = args.iter().map(String::as_str).collect();

        let config = BenchConfig {
            command: "bench commands".into(),
            variant: Some(name.into()),
            input_file: Some(basename.clone()),
            input_mb: Some(file_mb),
            cargo_features: Some("zlib-ng".into()),
            cargo_profile: "release".into(),
            runs,
            cli_args: Some(crate::harness::format_cli_args(&binary.display().to_string(), &args_refs)),
            metadata: None,
        };

        harness.run_external(&config, binary, &args_refs, project_root)?;
    }

    Ok(())
}
